// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: fishjam/media_events/server/server.proto

package server

import (
	media_events "conference-to-stream/proto/fishjam/media_events"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaEvent_VadNotification_Status int32

const (
	MediaEvent_VadNotification_STATUS_UNSPECIFIED MediaEvent_VadNotification_Status = 0
	MediaEvent_VadNotification_STATUS_SILENCE     MediaEvent_VadNotification_Status = 1
	MediaEvent_VadNotification_STATUS_SPEECH      MediaEvent_VadNotification_Status = 2
)

// Enum value maps for MediaEvent_VadNotification_Status.
var (
	MediaEvent_VadNotification_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_SILENCE",
		2: "STATUS_SPEECH",
	}
	MediaEvent_VadNotification_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_SILENCE":     1,
		"STATUS_SPEECH":      2,
	}
)

func (x MediaEvent_VadNotification_Status) Enum() *MediaEvent_VadNotification_Status {
	p := new(MediaEvent_VadNotification_Status)
	*p = x
	return p
}

func (x MediaEvent_VadNotification_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaEvent_VadNotification_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_fishjam_media_events_server_server_proto_enumTypes[0].Descriptor()
}

func (MediaEvent_VadNotification_Status) Type() protoreflect.EnumType {
	return &file_fishjam_media_events_server_server_proto_enumTypes[0]
}

func (x MediaEvent_VadNotification_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaEvent_VadNotification_Status.Descriptor instead.
func (MediaEvent_VadNotification_Status) EnumDescriptor() ([]byte, []int) {
	return file_fishjam_media_events_server_server_proto_rawDescGZIP(), []int{0, 13, 0}
}

// Defines any type of message sent from Membrane RTC Engine to Peer
type MediaEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*MediaEvent_EndpointUpdated_
	//	*MediaEvent_TrackUpdated_
	//	*MediaEvent_TracksAdded_
	//	*MediaEvent_TracksRemoved_
	//	*MediaEvent_EndpointAdded_
	//	*MediaEvent_EndpointRemoved_
	//	*MediaEvent_Connected_
	//	*MediaEvent_Error_
	//	*MediaEvent_OfferData_
	//	*MediaEvent_Candidate
	//	*MediaEvent_SdpAnswer_
	//	*MediaEvent_VadNotification_
	//	*MediaEvent_TrackVariantSwitched_
	//	*MediaEvent_TrackVariantDisabled_
	//	*MediaEvent_TrackVariantEnabled_
	Content       isMediaEvent_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent) Reset() {
	*x = MediaEvent{}
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent) ProtoMessage() {}

func (x *MediaEvent) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent.ProtoReflect.Descriptor instead.
func (*MediaEvent) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_server_server_proto_rawDescGZIP(), []int{0}
}

func (x *MediaEvent) GetContent() isMediaEvent_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *MediaEvent) GetEndpointUpdated() *MediaEvent_EndpointUpdated {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_EndpointUpdated_); ok {
			return x.EndpointUpdated
		}
	}
	return nil
}

func (x *MediaEvent) GetTrackUpdated() *MediaEvent_TrackUpdated {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_TrackUpdated_); ok {
			return x.TrackUpdated
		}
	}
	return nil
}

func (x *MediaEvent) GetTracksAdded() *MediaEvent_TracksAdded {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_TracksAdded_); ok {
			return x.TracksAdded
		}
	}
	return nil
}

func (x *MediaEvent) GetTracksRemoved() *MediaEvent_TracksRemoved {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_TracksRemoved_); ok {
			return x.TracksRemoved
		}
	}
	return nil
}

func (x *MediaEvent) GetEndpointAdded() *MediaEvent_EndpointAdded {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_EndpointAdded_); ok {
			return x.EndpointAdded
		}
	}
	return nil
}

func (x *MediaEvent) GetEndpointRemoved() *MediaEvent_EndpointRemoved {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_EndpointRemoved_); ok {
			return x.EndpointRemoved
		}
	}
	return nil
}

func (x *MediaEvent) GetConnected() *MediaEvent_Connected {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_Connected_); ok {
			return x.Connected
		}
	}
	return nil
}

func (x *MediaEvent) GetError() *MediaEvent_Error {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_Error_); ok {
			return x.Error
		}
	}
	return nil
}

func (x *MediaEvent) GetOfferData() *MediaEvent_OfferData {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_OfferData_); ok {
			return x.OfferData
		}
	}
	return nil
}

func (x *MediaEvent) GetCandidate() *media_events.Candidate {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_Candidate); ok {
			return x.Candidate
		}
	}
	return nil
}

func (x *MediaEvent) GetSdpAnswer() *MediaEvent_SdpAnswer {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_SdpAnswer_); ok {
			return x.SdpAnswer
		}
	}
	return nil
}

func (x *MediaEvent) GetVadNotification() *MediaEvent_VadNotification {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_VadNotification_); ok {
			return x.VadNotification
		}
	}
	return nil
}

func (x *MediaEvent) GetTrackVariantSwitched() *MediaEvent_TrackVariantSwitched {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_TrackVariantSwitched_); ok {
			return x.TrackVariantSwitched
		}
	}
	return nil
}

func (x *MediaEvent) GetTrackVariantDisabled() *MediaEvent_TrackVariantDisabled {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_TrackVariantDisabled_); ok {
			return x.TrackVariantDisabled
		}
	}
	return nil
}

func (x *MediaEvent) GetTrackVariantEnabled() *MediaEvent_TrackVariantEnabled {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_TrackVariantEnabled_); ok {
			return x.TrackVariantEnabled
		}
	}
	return nil
}

type isMediaEvent_Content interface {
	isMediaEvent_Content()
}

type MediaEvent_EndpointUpdated_ struct {
	EndpointUpdated *MediaEvent_EndpointUpdated `protobuf:"bytes,1,opt,name=endpoint_updated,json=endpointUpdated,proto3,oneof"`
}

type MediaEvent_TrackUpdated_ struct {
	TrackUpdated *MediaEvent_TrackUpdated `protobuf:"bytes,2,opt,name=track_updated,json=trackUpdated,proto3,oneof"`
}

type MediaEvent_TracksAdded_ struct {
	TracksAdded *MediaEvent_TracksAdded `protobuf:"bytes,3,opt,name=tracks_added,json=tracksAdded,proto3,oneof"`
}

type MediaEvent_TracksRemoved_ struct {
	TracksRemoved *MediaEvent_TracksRemoved `protobuf:"bytes,4,opt,name=tracks_removed,json=tracksRemoved,proto3,oneof"`
}

type MediaEvent_EndpointAdded_ struct {
	EndpointAdded *MediaEvent_EndpointAdded `protobuf:"bytes,5,opt,name=endpoint_added,json=endpointAdded,proto3,oneof"`
}

type MediaEvent_EndpointRemoved_ struct {
	EndpointRemoved *MediaEvent_EndpointRemoved `protobuf:"bytes,6,opt,name=endpoint_removed,json=endpointRemoved,proto3,oneof"`
}

type MediaEvent_Connected_ struct {
	Connected *MediaEvent_Connected `protobuf:"bytes,7,opt,name=connected,proto3,oneof"`
}

type MediaEvent_Error_ struct {
	Error *MediaEvent_Error `protobuf:"bytes,8,opt,name=error,proto3,oneof"`
}

type MediaEvent_OfferData_ struct {
	OfferData *MediaEvent_OfferData `protobuf:"bytes,9,opt,name=offer_data,json=offerData,proto3,oneof"`
}

type MediaEvent_Candidate struct {
	Candidate *media_events.Candidate `protobuf:"bytes,10,opt,name=candidate,proto3,oneof"`
}

type MediaEvent_SdpAnswer_ struct {
	SdpAnswer *MediaEvent_SdpAnswer `protobuf:"bytes,11,opt,name=sdp_answer,json=sdpAnswer,proto3,oneof"`
}

type MediaEvent_VadNotification_ struct {
	VadNotification *MediaEvent_VadNotification `protobuf:"bytes,12,opt,name=vad_notification,json=vadNotification,proto3,oneof"`
}

type MediaEvent_TrackVariantSwitched_ struct {
	TrackVariantSwitched *MediaEvent_TrackVariantSwitched `protobuf:"bytes,13,opt,name=track_variant_switched,json=trackVariantSwitched,proto3,oneof"`
}

type MediaEvent_TrackVariantDisabled_ struct {
	TrackVariantDisabled *MediaEvent_TrackVariantDisabled `protobuf:"bytes,14,opt,name=track_variant_disabled,json=trackVariantDisabled,proto3,oneof"`
}

type MediaEvent_TrackVariantEnabled_ struct {
	TrackVariantEnabled *MediaEvent_TrackVariantEnabled `protobuf:"bytes,15,opt,name=track_variant_enabled,json=trackVariantEnabled,proto3,oneof"`
}

func (*MediaEvent_EndpointUpdated_) isMediaEvent_Content() {}

func (*MediaEvent_TrackUpdated_) isMediaEvent_Content() {}

func (*MediaEvent_TracksAdded_) isMediaEvent_Content() {}

func (*MediaEvent_TracksRemoved_) isMediaEvent_Content() {}

func (*MediaEvent_EndpointAdded_) isMediaEvent_Content() {}

func (*MediaEvent_EndpointRemoved_) isMediaEvent_Content() {}

func (*MediaEvent_Connected_) isMediaEvent_Content() {}

func (*MediaEvent_Error_) isMediaEvent_Content() {}

func (*MediaEvent_OfferData_) isMediaEvent_Content() {}

func (*MediaEvent_Candidate) isMediaEvent_Content() {}

func (*MediaEvent_SdpAnswer_) isMediaEvent_Content() {}

func (*MediaEvent_VadNotification_) isMediaEvent_Content() {}

func (*MediaEvent_TrackVariantSwitched_) isMediaEvent_Content() {}

func (*MediaEvent_TrackVariantDisabled_) isMediaEvent_Content() {}

func (*MediaEvent_TrackVariantEnabled_) isMediaEvent_Content() {}

// SCHEMAS
type MediaEvent_Track struct {
	state           protoimpl.MessageState            `protogen:"open.v1"`
	MetadataJson    string                            `protobuf:"bytes,1,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	SimulcastConfig *MediaEvent_Track_SimulcastConfig `protobuf:"bytes,2,opt,name=simulcast_config,json=simulcastConfig,proto3" json:"simulcast_config,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MediaEvent_Track) Reset() {
	*x = MediaEvent_Track{}
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_Track) ProtoMessage() {}

func (x *MediaEvent_Track) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_Track.ProtoReflect.Descriptor instead.
func (*MediaEvent_Track) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_server_server_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MediaEvent_Track) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *MediaEvent_Track) GetSimulcastConfig() *MediaEvent_Track_SimulcastConfig {
	if x != nil {
		return x.SimulcastConfig
	}
	return nil
}

type MediaEvent_Endpoint struct {
	state          protoimpl.MessageState       `protogen:"open.v1"`
	EndpointType   string                       `protobuf:"bytes,2,opt,name=endpoint_type,json=endpointType,proto3" json:"endpoint_type,omitempty"`
	MetadataJson   string                       `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	TrackIdToTrack map[string]*MediaEvent_Track `protobuf:"bytes,4,rep,name=track_id_to_track,json=trackIdToTrack,proto3" json:"track_id_to_track,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MediaEvent_Endpoint) Reset() {
	*x = MediaEvent_Endpoint{}
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_Endpoint) ProtoMessage() {}

func (x *MediaEvent_Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_Endpoint.ProtoReflect.Descriptor instead.
func (*MediaEvent_Endpoint) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_server_server_proto_rawDescGZIP(), []int{0, 1}
}

func (x *MediaEvent_Endpoint) GetEndpointType() string {
	if x != nil {
		return x.EndpointType
	}
	return ""
}

func (x *MediaEvent_Endpoint) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *MediaEvent_Endpoint) GetTrackIdToTrack() map[string]*MediaEvent_Track {
	if x != nil {
		return x.TrackIdToTrack
	}
	return nil
}

type MediaEvent_IceServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    string                 `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	Urls          []string               `protobuf:"bytes,2,rep,name=urls,proto3" json:"urls,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent_IceServer) Reset() {
	*x = MediaEvent_IceServer{}
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_IceServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_IceServer) ProtoMessage() {}

func (x *MediaEvent_IceServer) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_IceServer.ProtoReflect.Descriptor instead.
func (*MediaEvent_IceServer) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_server_server_proto_rawDescGZIP(), []int{0, 2}
}

func (x *MediaEvent_IceServer) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

func (x *MediaEvent_IceServer) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *MediaEvent_IceServer) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// Sent when metadata of one of the endpoints was updated
type MediaEvent_EndpointUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,2,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent_EndpointUpdated) Reset() {
	*x = MediaEvent_EndpointUpdated{}
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_EndpointUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_EndpointUpdated) ProtoMessage() {}

func (x *MediaEvent_EndpointUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_EndpointUpdated.ProtoReflect.Descriptor instead.
func (*MediaEvent_EndpointUpdated) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_server_server_proto_rawDescGZIP(), []int{0, 3}
}

func (x *MediaEvent_EndpointUpdated) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *MediaEvent_EndpointUpdated) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

// Sent when metadata of one of the tracks was updated
type MediaEvent_TrackUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	TrackId       string                 `protobuf:"bytes,2,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent_TrackUpdated) Reset() {
	*x = MediaEvent_TrackUpdated{}
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_TrackUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_TrackUpdated) ProtoMessage() {}

func (x *MediaEvent_TrackUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_TrackUpdated.ProtoReflect.Descriptor instead.
func (*MediaEvent_TrackUpdated) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_server_server_proto_rawDescGZIP(), []int{0, 4}
}

func (x *MediaEvent_TrackUpdated) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *MediaEvent_TrackUpdated) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *MediaEvent_TrackUpdated) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

// Sent to informs that one of the peers has added one or more tracks.
type MediaEvent_TracksAdded struct {
	state          protoimpl.MessageState       `protogen:"open.v1"`
	EndpointId     string                       `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	TrackIdToTrack map[string]*MediaEvent_Track `protobuf:"bytes,2,rep,name=track_id_to_track,json=trackIdToTrack,proto3" json:"track_id_to_track,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MediaEvent_TracksAdded) Reset() {
	*x = MediaEvent_TracksAdded{}
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_TracksAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_TracksAdded) ProtoMessage() {}

func (x *MediaEvent_TracksAdded) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_TracksAdded.ProtoReflect.Descriptor instead.
func (*MediaEvent_TracksAdded) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_server_server_proto_rawDescGZIP(), []int{0, 5}
}

func (x *MediaEvent_TracksAdded) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *MediaEvent_TracksAdded) GetTrackIdToTrack() map[string]*MediaEvent_Track {
	if x != nil {
		return x.TrackIdToTrack
	}
	return nil
}

// Sent to informs that one of the peers has removed one or more tracks.
type MediaEvent_TracksRemoved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	TrackIds      []string               `protobuf:"bytes,2,rep,name=track_ids,json=trackIds,proto3" json:"track_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent_TracksRemoved) Reset() {
	*x = MediaEvent_TracksRemoved{}
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_TracksRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_TracksRemoved) ProtoMessage() {}

func (x *MediaEvent_TracksRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_TracksRemoved.ProtoReflect.Descriptor instead.
func (*MediaEvent_TracksRemoved) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_server_server_proto_rawDescGZIP(), []int{0, 6}
}

func (x *MediaEvent_TracksRemoved) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *MediaEvent_TracksRemoved) GetTrackIds() []string {
	if x != nil {
		return x.TrackIds
	}
	return nil
}

// Sent to all peers in the room after a new endpoint was added.
type MediaEvent_EndpointAdded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,2,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent_EndpointAdded) Reset() {
	*x = MediaEvent_EndpointAdded{}
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_EndpointAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_EndpointAdded) ProtoMessage() {}

func (x *MediaEvent_EndpointAdded) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_EndpointAdded.ProtoReflect.Descriptor instead.
func (*MediaEvent_EndpointAdded) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_server_server_proto_rawDescGZIP(), []int{0, 7}
}

func (x *MediaEvent_EndpointAdded) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *MediaEvent_EndpointAdded) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

// Sent to the peer after connecting to the WebRTC Endpoint.
type MediaEvent_Connected struct {
	state                protoimpl.MessageState          `protogen:"open.v1"`
	EndpointId           string                          `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	EndpointIdToEndpoint map[string]*MediaEvent_Endpoint `protobuf:"bytes,2,rep,name=endpoint_id_to_endpoint,json=endpointIdToEndpoint,proto3" json:"endpoint_id_to_endpoint,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IceServers           []*MediaEvent_IceServer         `protobuf:"bytes,3,rep,name=ice_servers,json=iceServers,proto3" json:"ice_servers,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MediaEvent_Connected) Reset() {
	*x = MediaEvent_Connected{}
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_Connected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_Connected) ProtoMessage() {}

func (x *MediaEvent_Connected) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_Connected.ProtoReflect.Descriptor instead.
func (*MediaEvent_Connected) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_server_server_proto_rawDescGZIP(), []int{0, 8}
}

func (x *MediaEvent_Connected) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *MediaEvent_Connected) GetEndpointIdToEndpoint() map[string]*MediaEvent_Endpoint {
	if x != nil {
		return x.EndpointIdToEndpoint
	}
	return nil
}

func (x *MediaEvent_Connected) GetIceServers() []*MediaEvent_IceServer {
	if x != nil {
		return x.IceServers
	}
	return nil
}

// Sent to all remaining peers in the room after some endpoint was removed.
type MediaEvent_EndpointRemoved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent_EndpointRemoved) Reset() {
	*x = MediaEvent_EndpointRemoved{}
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_EndpointRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_EndpointRemoved) ProtoMessage() {}

func (x *MediaEvent_EndpointRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_EndpointRemoved.ProtoReflect.Descriptor instead.
func (*MediaEvent_EndpointRemoved) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_server_server_proto_rawDescGZIP(), []int{0, 9}
}

func (x *MediaEvent_EndpointRemoved) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

// Sent to inform that an error occurred on the server providing a message to show
type MediaEvent_Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent_Error) Reset() {
	*x = MediaEvent_Error{}
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_Error) ProtoMessage() {}

func (x *MediaEvent_Error) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_Error.ProtoReflect.Descriptor instead.
func (*MediaEvent_Error) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_server_server_proto_rawDescGZIP(), []int{0, 10}
}

func (x *MediaEvent_Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Sent to inform about the number of audio and video tracks that will be sent from the engine to the peer
type MediaEvent_OfferData struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	TracksTypes   *MediaEvent_OfferData_TrackTypes `protobuf:"bytes,1,opt,name=tracks_types,json=tracksTypes,proto3" json:"tracks_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent_OfferData) Reset() {
	*x = MediaEvent_OfferData{}
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_OfferData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_OfferData) ProtoMessage() {}

func (x *MediaEvent_OfferData) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_OfferData.ProtoReflect.Descriptor instead.
func (*MediaEvent_OfferData) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_server_server_proto_rawDescGZIP(), []int{0, 11}
}

func (x *MediaEvent_OfferData) GetTracksTypes() *MediaEvent_OfferData_TrackTypes {
	if x != nil {
		return x.TracksTypes
	}
	return nil
}

// Sent after receiving `SdpOffer` from Peer
type MediaEvent_SdpAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sdp           string                 `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"` // The value of the `sessionDescription.sdp`
	MidToTrackId  map[string]string      `protobuf:"bytes,2,rep,name=mid_to_track_id,json=midToTrackId,proto3" json:"mid_to_track_id,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent_SdpAnswer) Reset() {
	*x = MediaEvent_SdpAnswer{}
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_SdpAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_SdpAnswer) ProtoMessage() {}

func (x *MediaEvent_SdpAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_SdpAnswer.ProtoReflect.Descriptor instead.
func (*MediaEvent_SdpAnswer) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_server_server_proto_rawDescGZIP(), []int{0, 12}
}

func (x *MediaEvent_SdpAnswer) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

func (x *MediaEvent_SdpAnswer) GetMidToTrackId() map[string]string {
	if x != nil {
		return x.MidToTrackId
	}
	return nil
}

// Sent to inform that the track denoted by `trackId` has changed their voice activity
// For this notification to work, the server must be configured to use VAD extension
// and the sender must support it.
type MediaEvent_VadNotification struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	TrackId       string                            `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	Status        MediaEvent_VadNotification_Status `protobuf:"varint,2,opt,name=status,proto3,enum=fishjam.media_events.server.MediaEvent_VadNotification_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent_VadNotification) Reset() {
	*x = MediaEvent_VadNotification{}
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_VadNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_VadNotification) ProtoMessage() {}

func (x *MediaEvent_VadNotification) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_VadNotification.ProtoReflect.Descriptor instead.
func (*MediaEvent_VadNotification) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_server_server_proto_rawDescGZIP(), []int{0, 13}
}

func (x *MediaEvent_VadNotification) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *MediaEvent_VadNotification) GetStatus() MediaEvent_VadNotification_Status {
	if x != nil {
		return x.Status
	}
	return MediaEvent_VadNotification_STATUS_UNSPECIFIED
}

// Informs that track's variant has been changed
type MediaEvent_TrackVariantSwitched struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	TrackId       string                 `protobuf:"bytes,2,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	Variant       media_events.Variant   `protobuf:"varint,3,opt,name=variant,proto3,enum=fishjam.media_events.Variant" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent_TrackVariantSwitched) Reset() {
	*x = MediaEvent_TrackVariantSwitched{}
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_TrackVariantSwitched) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_TrackVariantSwitched) ProtoMessage() {}

func (x *MediaEvent_TrackVariantSwitched) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_TrackVariantSwitched.ProtoReflect.Descriptor instead.
func (*MediaEvent_TrackVariantSwitched) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_server_server_proto_rawDescGZIP(), []int{0, 14}
}

func (x *MediaEvent_TrackVariantSwitched) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *MediaEvent_TrackVariantSwitched) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *MediaEvent_TrackVariantSwitched) GetVariant() media_events.Variant {
	if x != nil {
		return x.Variant
	}
	return media_events.Variant(0)
}

// Sent when track's variant has been disabled
type MediaEvent_TrackVariantDisabled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	TrackId       string                 `protobuf:"bytes,2,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	Variant       media_events.Variant   `protobuf:"varint,3,opt,name=variant,proto3,enum=fishjam.media_events.Variant" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent_TrackVariantDisabled) Reset() {
	*x = MediaEvent_TrackVariantDisabled{}
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_TrackVariantDisabled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_TrackVariantDisabled) ProtoMessage() {}

func (x *MediaEvent_TrackVariantDisabled) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_TrackVariantDisabled.ProtoReflect.Descriptor instead.
func (*MediaEvent_TrackVariantDisabled) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_server_server_proto_rawDescGZIP(), []int{0, 15}
}

func (x *MediaEvent_TrackVariantDisabled) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *MediaEvent_TrackVariantDisabled) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *MediaEvent_TrackVariantDisabled) GetVariant() media_events.Variant {
	if x != nil {
		return x.Variant
	}
	return media_events.Variant(0)
}

// Sent when track's variant has been enabled
type MediaEvent_TrackVariantEnabled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	TrackId       string                 `protobuf:"bytes,2,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	Variant       media_events.Variant   `protobuf:"varint,3,opt,name=variant,proto3,enum=fishjam.media_events.Variant" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent_TrackVariantEnabled) Reset() {
	*x = MediaEvent_TrackVariantEnabled{}
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_TrackVariantEnabled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_TrackVariantEnabled) ProtoMessage() {}

func (x *MediaEvent_TrackVariantEnabled) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_TrackVariantEnabled.ProtoReflect.Descriptor instead.
func (*MediaEvent_TrackVariantEnabled) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_server_server_proto_rawDescGZIP(), []int{0, 16}
}

func (x *MediaEvent_TrackVariantEnabled) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *MediaEvent_TrackVariantEnabled) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *MediaEvent_TrackVariantEnabled) GetVariant() media_events.Variant {
	if x != nil {
		return x.Variant
	}
	return media_events.Variant(0)
}

type MediaEvent_Track_SimulcastConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Enabled          bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	EnabledVariants  []media_events.Variant `protobuf:"varint,2,rep,packed,name=enabled_variants,json=enabledVariants,proto3,enum=fishjam.media_events.Variant" json:"enabled_variants,omitempty"`
	DisabledVariants []media_events.Variant `protobuf:"varint,3,rep,packed,name=disabled_variants,json=disabledVariants,proto3,enum=fishjam.media_events.Variant" json:"disabled_variants,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MediaEvent_Track_SimulcastConfig) Reset() {
	*x = MediaEvent_Track_SimulcastConfig{}
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_Track_SimulcastConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_Track_SimulcastConfig) ProtoMessage() {}

func (x *MediaEvent_Track_SimulcastConfig) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_Track_SimulcastConfig.ProtoReflect.Descriptor instead.
func (*MediaEvent_Track_SimulcastConfig) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_server_server_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *MediaEvent_Track_SimulcastConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *MediaEvent_Track_SimulcastConfig) GetEnabledVariants() []media_events.Variant {
	if x != nil {
		return x.EnabledVariants
	}
	return nil
}

func (x *MediaEvent_Track_SimulcastConfig) GetDisabledVariants() []media_events.Variant {
	if x != nil {
		return x.DisabledVariants
	}
	return nil
}

type MediaEvent_OfferData_TrackTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audio         int32                  `protobuf:"varint,1,opt,name=audio,proto3" json:"audio,omitempty"`
	Video         int32                  `protobuf:"varint,2,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent_OfferData_TrackTypes) Reset() {
	*x = MediaEvent_OfferData_TrackTypes{}
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_OfferData_TrackTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_OfferData_TrackTypes) ProtoMessage() {}

func (x *MediaEvent_OfferData_TrackTypes) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_server_server_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_OfferData_TrackTypes.ProtoReflect.Descriptor instead.
func (*MediaEvent_OfferData_TrackTypes) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_server_server_proto_rawDescGZIP(), []int{0, 11, 0}
}

func (x *MediaEvent_OfferData_TrackTypes) GetAudio() int32 {
	if x != nil {
		return x.Audio
	}
	return 0
}

func (x *MediaEvent_OfferData_TrackTypes) GetVideo() int32 {
	if x != nil {
		return x.Video
	}
	return 0
}

var File_fishjam_media_events_server_server_proto protoreflect.FileDescriptor

const file_fishjam_media_events_server_server_proto_rawDesc = "" +
	"\n" +
	"(fishjam/media_events/server/server.proto\x12\x1bfishjam.media_events.server\x1a!fishjam/media_events/shared.proto\"\xe6!\n" +
	"\n" +
	"MediaEvent\x12d\n" +
	"\x10endpoint_updated\x18\x01 \x01(\v27.fishjam.media_events.server.MediaEvent.EndpointUpdatedH\x00R\x0fendpointUpdated\x12[\n" +
	"\rtrack_updated\x18\x02 \x01(\v24.fishjam.media_events.server.MediaEvent.TrackUpdatedH\x00R\ftrackUpdated\x12X\n" +
	"\ftracks_added\x18\x03 \x01(\v23.fishjam.media_events.server.MediaEvent.TracksAddedH\x00R\vtracksAdded\x12^\n" +
	"\x0etracks_removed\x18\x04 \x01(\v25.fishjam.media_events.server.MediaEvent.TracksRemovedH\x00R\rtracksRemoved\x12^\n" +
	"\x0eendpoint_added\x18\x05 \x01(\v25.fishjam.media_events.server.MediaEvent.EndpointAddedH\x00R\rendpointAdded\x12d\n" +
	"\x10endpoint_removed\x18\x06 \x01(\v27.fishjam.media_events.server.MediaEvent.EndpointRemovedH\x00R\x0fendpointRemoved\x12Q\n" +
	"\tconnected\x18\a \x01(\v21.fishjam.media_events.server.MediaEvent.ConnectedH\x00R\tconnected\x12E\n" +
	"\x05error\x18\b \x01(\v2-.fishjam.media_events.server.MediaEvent.ErrorH\x00R\x05error\x12R\n" +
	"\n" +
	"offer_data\x18\t \x01(\v21.fishjam.media_events.server.MediaEvent.OfferDataH\x00R\tofferData\x12?\n" +
	"\tcandidate\x18\n" +
	" \x01(\v2\x1f.fishjam.media_events.CandidateH\x00R\tcandidate\x12R\n" +
	"\n" +
	"sdp_answer\x18\v \x01(\v21.fishjam.media_events.server.MediaEvent.SdpAnswerH\x00R\tsdpAnswer\x12d\n" +
	"\x10vad_notification\x18\f \x01(\v27.fishjam.media_events.server.MediaEvent.VadNotificationH\x00R\x0fvadNotification\x12t\n" +
	"\x16track_variant_switched\x18\r \x01(\v2<.fishjam.media_events.server.MediaEvent.TrackVariantSwitchedH\x00R\x14trackVariantSwitched\x12t\n" +
	"\x16track_variant_disabled\x18\x0e \x01(\v2<.fishjam.media_events.server.MediaEvent.TrackVariantDisabledH\x00R\x14trackVariantDisabled\x12q\n" +
	"\x15track_variant_enabled\x18\x0f \x01(\v2;.fishjam.media_events.server.MediaEvent.TrackVariantEnabledH\x00R\x13trackVariantEnabled\x1a\xda\x02\n" +
	"\x05Track\x12#\n" +
	"\rmetadata_json\x18\x01 \x01(\tR\fmetadataJson\x12h\n" +
	"\x10simulcast_config\x18\x02 \x01(\v2=.fishjam.media_events.server.MediaEvent.Track.SimulcastConfigR\x0fsimulcastConfig\x1a\xc1\x01\n" +
	"\x0fSimulcastConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12H\n" +
	"\x10enabled_variants\x18\x02 \x03(\x0e2\x1d.fishjam.media_events.VariantR\x0fenabledVariants\x12J\n" +
	"\x11disabled_variants\x18\x03 \x03(\x0e2\x1d.fishjam.media_events.VariantR\x10disabledVariants\x1a\xb7\x02\n" +
	"\bEndpoint\x12#\n" +
	"\rendpoint_type\x18\x02 \x01(\tR\fendpointType\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\tR\fmetadataJson\x12o\n" +
	"\x11track_id_to_track\x18\x04 \x03(\v2D.fishjam.media_events.server.MediaEvent.Endpoint.TrackIdToTrackEntryR\x0etrackIdToTrack\x1ap\n" +
	"\x13TrackIdToTrackEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12C\n" +
	"\x05value\x18\x02 \x01(\v2-.fishjam.media_events.server.MediaEvent.TrackR\x05value:\x028\x01\x1a[\n" +
	"\tIceServer\x12\x1e\n" +
	"\n" +
	"credential\x18\x01 \x01(\tR\n" +
	"credential\x12\x12\n" +
	"\x04urls\x18\x02 \x03(\tR\x04urls\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x1aW\n" +
	"\x0fEndpointUpdated\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12#\n" +
	"\rmetadata_json\x18\x02 \x01(\tR\fmetadataJson\x1ao\n" +
	"\fTrackUpdated\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12\x19\n" +
	"\btrack_id\x18\x02 \x01(\tR\atrackId\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\tR\fmetadataJson\x1a\x94\x02\n" +
	"\vTracksAdded\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12r\n" +
	"\x11track_id_to_track\x18\x02 \x03(\v2G.fishjam.media_events.server.MediaEvent.TracksAdded.TrackIdToTrackEntryR\x0etrackIdToTrack\x1ap\n" +
	"\x13TrackIdToTrackEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12C\n" +
	"\x05value\x18\x02 \x01(\v2-.fishjam.media_events.server.MediaEvent.TrackR\x05value:\x028\x01\x1aM\n" +
	"\rTracksRemoved\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12\x1b\n" +
	"\ttrack_ids\x18\x02 \x03(\tR\btrackIds\x1aU\n" +
	"\rEndpointAdded\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12#\n" +
	"\rmetadata_json\x18\x02 \x01(\tR\fmetadataJson\x1a\x80\x03\n" +
	"\tConnected\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12\x82\x01\n" +
	"\x17endpoint_id_to_endpoint\x18\x02 \x03(\v2K.fishjam.media_events.server.MediaEvent.Connected.EndpointIdToEndpointEntryR\x14endpointIdToEndpoint\x12R\n" +
	"\vice_servers\x18\x03 \x03(\v21.fishjam.media_events.server.MediaEvent.IceServerR\n" +
	"iceServers\x1ay\n" +
	"\x19EndpointIdToEndpointEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12F\n" +
	"\x05value\x18\x02 \x01(\v20.fishjam.media_events.server.MediaEvent.EndpointR\x05value:\x028\x01\x1a2\n" +
	"\x0fEndpointRemoved\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x1a!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x1a\xa6\x01\n" +
	"\tOfferData\x12_\n" +
	"\ftracks_types\x18\x01 \x01(\v2<.fishjam.media_events.server.MediaEvent.OfferData.TrackTypesR\vtracksTypes\x1a8\n" +
	"\n" +
	"TrackTypes\x12\x14\n" +
	"\x05audio\x18\x01 \x01(\x05R\x05audio\x12\x14\n" +
	"\x05video\x18\x02 \x01(\x05R\x05video\x1a\xca\x01\n" +
	"\tSdpAnswer\x12\x10\n" +
	"\x03sdp\x18\x01 \x01(\tR\x03sdp\x12j\n" +
	"\x0fmid_to_track_id\x18\x02 \x03(\v2C.fishjam.media_events.server.MediaEvent.SdpAnswer.MidToTrackIdEntryR\fmidToTrackId\x1a?\n" +
	"\x11MidToTrackIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\xcd\x01\n" +
	"\x0fVadNotification\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\x12V\n" +
	"\x06status\x18\x02 \x01(\x0e2>.fishjam.media_events.server.MediaEvent.VadNotification.StatusR\x06status\"G\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_SILENCE\x10\x01\x12\x11\n" +
	"\rSTATUS_SPEECH\x10\x02\x1a\x8b\x01\n" +
	"\x14TrackVariantSwitched\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12\x19\n" +
	"\btrack_id\x18\x02 \x01(\tR\atrackId\x127\n" +
	"\avariant\x18\x03 \x01(\x0e2\x1d.fishjam.media_events.VariantR\avariant\x1a\x8b\x01\n" +
	"\x14TrackVariantDisabled\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12\x19\n" +
	"\btrack_id\x18\x02 \x01(\tR\atrackId\x127\n" +
	"\avariant\x18\x03 \x01(\x0e2\x1d.fishjam.media_events.VariantR\avariant\x1a\x8a\x01\n" +
	"\x13TrackVariantEnabled\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12\x19\n" +
	"\btrack_id\x18\x02 \x01(\tR\atrackId\x127\n" +
	"\avariant\x18\x03 \x01(\x0e2\x1d.fishjam.media_events.VariantR\avariantB\t\n" +
	"\acontentB8Z6conference-to-stream/proto/fishjam/media_events/serverb\x06proto3"

var (
	file_fishjam_media_events_server_server_proto_rawDescOnce sync.Once
	file_fishjam_media_events_server_server_proto_rawDescData []byte
)

func file_fishjam_media_events_server_server_proto_rawDescGZIP() []byte {
	file_fishjam_media_events_server_server_proto_rawDescOnce.Do(func() {
		file_fishjam_media_events_server_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fishjam_media_events_server_server_proto_rawDesc), len(file_fishjam_media_events_server_server_proto_rawDesc)))
	})
	return file_fishjam_media_events_server_server_proto_rawDescData
}

var file_fishjam_media_events_server_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fishjam_media_events_server_server_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_fishjam_media_events_server_server_proto_goTypes = []any{
	(MediaEvent_VadNotification_Status)(0),   // 0: fishjam.media_events.server.MediaEvent.VadNotification.Status
	(*MediaEvent)(nil),                       // 1: fishjam.media_events.server.MediaEvent
	(*MediaEvent_Track)(nil),                 // 2: fishjam.media_events.server.MediaEvent.Track
	(*MediaEvent_Endpoint)(nil),              // 3: fishjam.media_events.server.MediaEvent.Endpoint
	(*MediaEvent_IceServer)(nil),             // 4: fishjam.media_events.server.MediaEvent.IceServer
	(*MediaEvent_EndpointUpdated)(nil),       // 5: fishjam.media_events.server.MediaEvent.EndpointUpdated
	(*MediaEvent_TrackUpdated)(nil),          // 6: fishjam.media_events.server.MediaEvent.TrackUpdated
	(*MediaEvent_TracksAdded)(nil),           // 7: fishjam.media_events.server.MediaEvent.TracksAdded
	(*MediaEvent_TracksRemoved)(nil),         // 8: fishjam.media_events.server.MediaEvent.TracksRemoved
	(*MediaEvent_EndpointAdded)(nil),         // 9: fishjam.media_events.server.MediaEvent.EndpointAdded
	(*MediaEvent_Connected)(nil),             // 10: fishjam.media_events.server.MediaEvent.Connected
	(*MediaEvent_EndpointRemoved)(nil),       // 11: fishjam.media_events.server.MediaEvent.EndpointRemoved
	(*MediaEvent_Error)(nil),                 // 12: fishjam.media_events.server.MediaEvent.Error
	(*MediaEvent_OfferData)(nil),             // 13: fishjam.media_events.server.MediaEvent.OfferData
	(*MediaEvent_SdpAnswer)(nil),             // 14: fishjam.media_events.server.MediaEvent.SdpAnswer
	(*MediaEvent_VadNotification)(nil),       // 15: fishjam.media_events.server.MediaEvent.VadNotification
	(*MediaEvent_TrackVariantSwitched)(nil),  // 16: fishjam.media_events.server.MediaEvent.TrackVariantSwitched
	(*MediaEvent_TrackVariantDisabled)(nil),  // 17: fishjam.media_events.server.MediaEvent.TrackVariantDisabled
	(*MediaEvent_TrackVariantEnabled)(nil),   // 18: fishjam.media_events.server.MediaEvent.TrackVariantEnabled
	(*MediaEvent_Track_SimulcastConfig)(nil), // 19: fishjam.media_events.server.MediaEvent.Track.SimulcastConfig
	nil,                                      // 20: fishjam.media_events.server.MediaEvent.Endpoint.TrackIdToTrackEntry
	nil,                                      // 21: fishjam.media_events.server.MediaEvent.TracksAdded.TrackIdToTrackEntry
	nil,                                      // 22: fishjam.media_events.server.MediaEvent.Connected.EndpointIdToEndpointEntry
	(*MediaEvent_OfferData_TrackTypes)(nil),  // 23: fishjam.media_events.server.MediaEvent.OfferData.TrackTypes
	nil,                                      // 24: fishjam.media_events.server.MediaEvent.SdpAnswer.MidToTrackIdEntry
	(*media_events.Candidate)(nil),           // 25: fishjam.media_events.Candidate
	(media_events.Variant)(0),                // 26: fishjam.media_events.Variant
}
var file_fishjam_media_events_server_server_proto_depIdxs = []int32{
	5,  // 0: fishjam.media_events.server.MediaEvent.endpoint_updated:type_name -> fishjam.media_events.server.MediaEvent.EndpointUpdated
	6,  // 1: fishjam.media_events.server.MediaEvent.track_updated:type_name -> fishjam.media_events.server.MediaEvent.TrackUpdated
	7,  // 2: fishjam.media_events.server.MediaEvent.tracks_added:type_name -> fishjam.media_events.server.MediaEvent.TracksAdded
	8,  // 3: fishjam.media_events.server.MediaEvent.tracks_removed:type_name -> fishjam.media_events.server.MediaEvent.TracksRemoved
	9,  // 4: fishjam.media_events.server.MediaEvent.endpoint_added:type_name -> fishjam.media_events.server.MediaEvent.EndpointAdded
	11, // 5: fishjam.media_events.server.MediaEvent.endpoint_removed:type_name -> fishjam.media_events.server.MediaEvent.EndpointRemoved
	10, // 6: fishjam.media_events.server.MediaEvent.connected:type_name -> fishjam.media_events.server.MediaEvent.Connected
	12, // 7: fishjam.media_events.server.MediaEvent.error:type_name -> fishjam.media_events.server.MediaEvent.Error
	13, // 8: fishjam.media_events.server.MediaEvent.offer_data:type_name -> fishjam.media_events.server.MediaEvent.OfferData
	25, // 9: fishjam.media_events.server.MediaEvent.candidate:type_name -> fishjam.media_events.Candidate
	14, // 10: fishjam.media_events.server.MediaEvent.sdp_answer:type_name -> fishjam.media_events.server.MediaEvent.SdpAnswer
	15, // 11: fishjam.media_events.server.MediaEvent.vad_notification:type_name -> fishjam.media_events.server.MediaEvent.VadNotification
	16, // 12: fishjam.media_events.server.MediaEvent.track_variant_switched:type_name -> fishjam.media_events.server.MediaEvent.TrackVariantSwitched
	17, // 13: fishjam.media_events.server.MediaEvent.track_variant_disabled:type_name -> fishjam.media_events.server.MediaEvent.TrackVariantDisabled
	18, // 14: fishjam.media_events.server.MediaEvent.track_variant_enabled:type_name -> fishjam.media_events.server.MediaEvent.TrackVariantEnabled
	19, // 15: fishjam.media_events.server.MediaEvent.Track.simulcast_config:type_name -> fishjam.media_events.server.MediaEvent.Track.SimulcastConfig
	20, // 16: fishjam.media_events.server.MediaEvent.Endpoint.track_id_to_track:type_name -> fishjam.media_events.server.MediaEvent.Endpoint.TrackIdToTrackEntry
	21, // 17: fishjam.media_events.server.MediaEvent.TracksAdded.track_id_to_track:type_name -> fishjam.media_events.server.MediaEvent.TracksAdded.TrackIdToTrackEntry
	22, // 18: fishjam.media_events.server.MediaEvent.Connected.endpoint_id_to_endpoint:type_name -> fishjam.media_events.server.MediaEvent.Connected.EndpointIdToEndpointEntry
	4,  // 19: fishjam.media_events.server.MediaEvent.Connected.ice_servers:type_name -> fishjam.media_events.server.MediaEvent.IceServer
	23, // 20: fishjam.media_events.server.MediaEvent.OfferData.tracks_types:type_name -> fishjam.media_events.server.MediaEvent.OfferData.TrackTypes
	24, // 21: fishjam.media_events.server.MediaEvent.SdpAnswer.mid_to_track_id:type_name -> fishjam.media_events.server.MediaEvent.SdpAnswer.MidToTrackIdEntry
	0,  // 22: fishjam.media_events.server.MediaEvent.VadNotification.status:type_name -> fishjam.media_events.server.MediaEvent.VadNotification.Status
	26, // 23: fishjam.media_events.server.MediaEvent.TrackVariantSwitched.variant:type_name -> fishjam.media_events.Variant
	26, // 24: fishjam.media_events.server.MediaEvent.TrackVariantDisabled.variant:type_name -> fishjam.media_events.Variant
	26, // 25: fishjam.media_events.server.MediaEvent.TrackVariantEnabled.variant:type_name -> fishjam.media_events.Variant
	26, // 26: fishjam.media_events.server.MediaEvent.Track.SimulcastConfig.enabled_variants:type_name -> fishjam.media_events.Variant
	26, // 27: fishjam.media_events.server.MediaEvent.Track.SimulcastConfig.disabled_variants:type_name -> fishjam.media_events.Variant
	2,  // 28: fishjam.media_events.server.MediaEvent.Endpoint.TrackIdToTrackEntry.value:type_name -> fishjam.media_events.server.MediaEvent.Track
	2,  // 29: fishjam.media_events.server.MediaEvent.TracksAdded.TrackIdToTrackEntry.value:type_name -> fishjam.media_events.server.MediaEvent.Track
	3,  // 30: fishjam.media_events.server.MediaEvent.Connected.EndpointIdToEndpointEntry.value:type_name -> fishjam.media_events.server.MediaEvent.Endpoint
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_fishjam_media_events_server_server_proto_init() }
func file_fishjam_media_events_server_server_proto_init() {
	if File_fishjam_media_events_server_server_proto != nil {
		return
	}
	file_fishjam_media_events_server_server_proto_msgTypes[0].OneofWrappers = []any{
		(*MediaEvent_EndpointUpdated_)(nil),
		(*MediaEvent_TrackUpdated_)(nil),
		(*MediaEvent_TracksAdded_)(nil),
		(*MediaEvent_TracksRemoved_)(nil),
		(*MediaEvent_EndpointAdded_)(nil),
		(*MediaEvent_EndpointRemoved_)(nil),
		(*MediaEvent_Connected_)(nil),
		(*MediaEvent_Error_)(nil),
		(*MediaEvent_OfferData_)(nil),
		(*MediaEvent_Candidate)(nil),
		(*MediaEvent_SdpAnswer_)(nil),
		(*MediaEvent_VadNotification_)(nil),
		(*MediaEvent_TrackVariantSwitched_)(nil),
		(*MediaEvent_TrackVariantDisabled_)(nil),
		(*MediaEvent_TrackVariantEnabled_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fishjam_media_events_server_server_proto_rawDesc), len(file_fishjam_media_events_server_server_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fishjam_media_events_server_server_proto_goTypes,
		DependencyIndexes: file_fishjam_media_events_server_server_proto_depIdxs,
		EnumInfos:         file_fishjam_media_events_server_server_proto_enumTypes,
		MessageInfos:      file_fishjam_media_events_server_server_proto_msgTypes,
	}.Build()
	File_fishjam_media_events_server_server_proto = out.File
	file_fishjam_media_events_server_server_proto_goTypes = nil
	file_fishjam_media_events_server_server_proto_depIdxs = nil
}
