// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: fishjam/media_events/peer/peer.proto

package peer

import (
	media_events "conference-to-stream/proto/fishjam/media_events"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defines any type of message sent from Peer to Membrane RTC Engine
type MediaEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*MediaEvent_Connect_
	//	*MediaEvent_Disconnect_
	//	*MediaEvent_UpdateEndpointMetadata_
	//	*MediaEvent_UpdateTrackMetadata_
	//	*MediaEvent_RenegotiateTracks_
	//	*MediaEvent_Candidate
	//	*MediaEvent_SdpOffer_
	//	*MediaEvent_TrackBitrates_
	//	*MediaEvent_EnableTrackVariant_
	//	*MediaEvent_DisableTrackVariant_
	//	*MediaEvent_SetTargetTrackVariant_
	//	*MediaEvent_UnmuteTrack_
	Content       isMediaEvent_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent) Reset() {
	*x = MediaEvent{}
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent) ProtoMessage() {}

func (x *MediaEvent) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent.ProtoReflect.Descriptor instead.
func (*MediaEvent) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_peer_peer_proto_rawDescGZIP(), []int{0}
}

func (x *MediaEvent) GetContent() isMediaEvent_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *MediaEvent) GetConnect() *MediaEvent_Connect {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_Connect_); ok {
			return x.Connect
		}
	}
	return nil
}

func (x *MediaEvent) GetDisconnect() *MediaEvent_Disconnect {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_Disconnect_); ok {
			return x.Disconnect
		}
	}
	return nil
}

func (x *MediaEvent) GetUpdateEndpointMetadata() *MediaEvent_UpdateEndpointMetadata {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_UpdateEndpointMetadata_); ok {
			return x.UpdateEndpointMetadata
		}
	}
	return nil
}

func (x *MediaEvent) GetUpdateTrackMetadata() *MediaEvent_UpdateTrackMetadata {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_UpdateTrackMetadata_); ok {
			return x.UpdateTrackMetadata
		}
	}
	return nil
}

func (x *MediaEvent) GetRenegotiateTracks() *MediaEvent_RenegotiateTracks {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_RenegotiateTracks_); ok {
			return x.RenegotiateTracks
		}
	}
	return nil
}

func (x *MediaEvent) GetCandidate() *media_events.Candidate {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_Candidate); ok {
			return x.Candidate
		}
	}
	return nil
}

func (x *MediaEvent) GetSdpOffer() *MediaEvent_SdpOffer {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_SdpOffer_); ok {
			return x.SdpOffer
		}
	}
	return nil
}

func (x *MediaEvent) GetTrackBitrates() *MediaEvent_TrackBitrates {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_TrackBitrates_); ok {
			return x.TrackBitrates
		}
	}
	return nil
}

func (x *MediaEvent) GetEnableTrackVariant() *MediaEvent_EnableTrackVariant {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_EnableTrackVariant_); ok {
			return x.EnableTrackVariant
		}
	}
	return nil
}

func (x *MediaEvent) GetDisableTrackVariant() *MediaEvent_DisableTrackVariant {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_DisableTrackVariant_); ok {
			return x.DisableTrackVariant
		}
	}
	return nil
}

func (x *MediaEvent) GetSetTargetTrackVariant() *MediaEvent_SetTargetTrackVariant {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_SetTargetTrackVariant_); ok {
			return x.SetTargetTrackVariant
		}
	}
	return nil
}

func (x *MediaEvent) GetUnmuteTrack() *MediaEvent_UnmuteTrack {
	if x != nil {
		if x, ok := x.Content.(*MediaEvent_UnmuteTrack_); ok {
			return x.UnmuteTrack
		}
	}
	return nil
}

type isMediaEvent_Content interface {
	isMediaEvent_Content()
}

type MediaEvent_Connect_ struct {
	Connect *MediaEvent_Connect `protobuf:"bytes,1,opt,name=connect,proto3,oneof"`
}

type MediaEvent_Disconnect_ struct {
	Disconnect *MediaEvent_Disconnect `protobuf:"bytes,2,opt,name=disconnect,proto3,oneof"`
}

type MediaEvent_UpdateEndpointMetadata_ struct {
	UpdateEndpointMetadata *MediaEvent_UpdateEndpointMetadata `protobuf:"bytes,3,opt,name=update_endpoint_metadata,json=updateEndpointMetadata,proto3,oneof"`
}

type MediaEvent_UpdateTrackMetadata_ struct {
	UpdateTrackMetadata *MediaEvent_UpdateTrackMetadata `protobuf:"bytes,4,opt,name=update_track_metadata,json=updateTrackMetadata,proto3,oneof"`
}

type MediaEvent_RenegotiateTracks_ struct {
	RenegotiateTracks *MediaEvent_RenegotiateTracks `protobuf:"bytes,5,opt,name=renegotiate_tracks,json=renegotiateTracks,proto3,oneof"`
}

type MediaEvent_Candidate struct {
	Candidate *media_events.Candidate `protobuf:"bytes,6,opt,name=candidate,proto3,oneof"`
}

type MediaEvent_SdpOffer_ struct {
	SdpOffer *MediaEvent_SdpOffer `protobuf:"bytes,7,opt,name=sdp_offer,json=sdpOffer,proto3,oneof"`
}

type MediaEvent_TrackBitrates_ struct {
	TrackBitrates *MediaEvent_TrackBitrates `protobuf:"bytes,8,opt,name=track_bitrates,json=trackBitrates,proto3,oneof"`
}

type MediaEvent_EnableTrackVariant_ struct {
	EnableTrackVariant *MediaEvent_EnableTrackVariant `protobuf:"bytes,9,opt,name=enable_track_variant,json=enableTrackVariant,proto3,oneof"`
}

type MediaEvent_DisableTrackVariant_ struct {
	DisableTrackVariant *MediaEvent_DisableTrackVariant `protobuf:"bytes,10,opt,name=disable_track_variant,json=disableTrackVariant,proto3,oneof"`
}

type MediaEvent_SetTargetTrackVariant_ struct {
	SetTargetTrackVariant *MediaEvent_SetTargetTrackVariant `protobuf:"bytes,11,opt,name=set_target_track_variant,json=setTargetTrackVariant,proto3,oneof"`
}

type MediaEvent_UnmuteTrack_ struct {
	UnmuteTrack *MediaEvent_UnmuteTrack `protobuf:"bytes,12,opt,name=unmute_track,json=unmuteTrack,proto3,oneof"`
}

func (*MediaEvent_Connect_) isMediaEvent_Content() {}

func (*MediaEvent_Disconnect_) isMediaEvent_Content() {}

func (*MediaEvent_UpdateEndpointMetadata_) isMediaEvent_Content() {}

func (*MediaEvent_UpdateTrackMetadata_) isMediaEvent_Content() {}

func (*MediaEvent_RenegotiateTracks_) isMediaEvent_Content() {}

func (*MediaEvent_Candidate) isMediaEvent_Content() {}

func (*MediaEvent_SdpOffer_) isMediaEvent_Content() {}

func (*MediaEvent_TrackBitrates_) isMediaEvent_Content() {}

func (*MediaEvent_EnableTrackVariant_) isMediaEvent_Content() {}

func (*MediaEvent_DisableTrackVariant_) isMediaEvent_Content() {}

func (*MediaEvent_SetTargetTrackVariant_) isMediaEvent_Content() {}

func (*MediaEvent_UnmuteTrack_) isMediaEvent_Content() {}

type MediaEvent_VariantBitrate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variant       media_events.Variant   `protobuf:"varint,1,opt,name=variant,proto3,enum=fishjam.media_events.Variant" json:"variant,omitempty"`
	Bitrate       int32                  `protobuf:"varint,2,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent_VariantBitrate) Reset() {
	*x = MediaEvent_VariantBitrate{}
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_VariantBitrate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_VariantBitrate) ProtoMessage() {}

func (x *MediaEvent_VariantBitrate) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_VariantBitrate.ProtoReflect.Descriptor instead.
func (*MediaEvent_VariantBitrate) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_peer_peer_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MediaEvent_VariantBitrate) GetVariant() media_events.Variant {
	if x != nil {
		return x.Variant
	}
	return media_events.Variant(0)
}

func (x *MediaEvent_VariantBitrate) GetBitrate() int32 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

// Sent when a peer wants to join WebRTC Endpoint.
type MediaEvent_Connect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetadataJson  string                 `protobuf:"bytes,1,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent_Connect) Reset() {
	*x = MediaEvent_Connect{}
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_Connect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_Connect) ProtoMessage() {}

func (x *MediaEvent_Connect) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_Connect.ProtoReflect.Descriptor instead.
func (*MediaEvent_Connect) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_peer_peer_proto_rawDescGZIP(), []int{0, 1}
}

func (x *MediaEvent_Connect) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

// Sent when a peer disconnects from WebRTC Endpoint.
type MediaEvent_Disconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent_Disconnect) Reset() {
	*x = MediaEvent_Disconnect{}
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_Disconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_Disconnect) ProtoMessage() {}

func (x *MediaEvent_Disconnect) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_Disconnect.ProtoReflect.Descriptor instead.
func (*MediaEvent_Disconnect) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_peer_peer_proto_rawDescGZIP(), []int{0, 2}
}

// Sent when a peer wants to update its metadata
type MediaEvent_UpdateEndpointMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetadataJson  string                 `protobuf:"bytes,1,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent_UpdateEndpointMetadata) Reset() {
	*x = MediaEvent_UpdateEndpointMetadata{}
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_UpdateEndpointMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_UpdateEndpointMetadata) ProtoMessage() {}

func (x *MediaEvent_UpdateEndpointMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_UpdateEndpointMetadata.ProtoReflect.Descriptor instead.
func (*MediaEvent_UpdateEndpointMetadata) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_peer_peer_proto_rawDescGZIP(), []int{0, 3}
}

func (x *MediaEvent_UpdateEndpointMetadata) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

// Sent when a peer wants to update its track's metadata
type MediaEvent_UpdateTrackMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,2,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent_UpdateTrackMetadata) Reset() {
	*x = MediaEvent_UpdateTrackMetadata{}
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_UpdateTrackMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_UpdateTrackMetadata) ProtoMessage() {}

func (x *MediaEvent_UpdateTrackMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_UpdateTrackMetadata.ProtoReflect.Descriptor instead.
func (*MediaEvent_UpdateTrackMetadata) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_peer_peer_proto_rawDescGZIP(), []int{0, 4}
}

func (x *MediaEvent_UpdateTrackMetadata) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *MediaEvent_UpdateTrackMetadata) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

// Sent when peer wants to renegotiate connection due to adding a track or removing a track
type MediaEvent_RenegotiateTracks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent_RenegotiateTracks) Reset() {
	*x = MediaEvent_RenegotiateTracks{}
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_RenegotiateTracks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_RenegotiateTracks) ProtoMessage() {}

func (x *MediaEvent_RenegotiateTracks) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_RenegotiateTracks.ProtoReflect.Descriptor instead.
func (*MediaEvent_RenegotiateTracks) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_peer_peer_proto_rawDescGZIP(), []int{0, 5}
}

// Sent as a response to `offerData` media event during renegotiation
// Maps contain only information about current peer's `sendonly` tracks.
// The "mid" is an identifier used to associate an RTP packet with an MLine from the SDP offer/answer.
type MediaEvent_SdpOffer struct {
	state                 protoimpl.MessageState               `protogen:"open.v1"`
	Sdp                   string                               `protobuf:"bytes,1,opt,name=sdp,proto3" json:"sdp,omitempty"` // The value of the `sessionDescription.sdp`
	TrackIdToMetadataJson map[string]string                    `protobuf:"bytes,2,rep,name=track_id_to_metadata_json,json=trackIdToMetadataJson,proto3" json:"track_id_to_metadata_json,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TrackIdToBitrates     map[string]*MediaEvent_TrackBitrates `protobuf:"bytes,3,rep,name=track_id_to_bitrates,json=trackIdToBitrates,proto3" json:"track_id_to_bitrates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Maps track_id to its bitrate. The track_id in the TrackBitrates message is ignored (we use the map key), so it can be omitted.
	MidToTrackId          map[string]string                    `protobuf:"bytes,4,rep,name=mid_to_track_id,json=midToTrackId,proto3" json:"mid_to_track_id,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *MediaEvent_SdpOffer) Reset() {
	*x = MediaEvent_SdpOffer{}
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_SdpOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_SdpOffer) ProtoMessage() {}

func (x *MediaEvent_SdpOffer) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_SdpOffer.ProtoReflect.Descriptor instead.
func (*MediaEvent_SdpOffer) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_peer_peer_proto_rawDescGZIP(), []int{0, 6}
}

func (x *MediaEvent_SdpOffer) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

func (x *MediaEvent_SdpOffer) GetTrackIdToMetadataJson() map[string]string {
	if x != nil {
		return x.TrackIdToMetadataJson
	}
	return nil
}

func (x *MediaEvent_SdpOffer) GetTrackIdToBitrates() map[string]*MediaEvent_TrackBitrates {
	if x != nil {
		return x.TrackIdToBitrates
	}
	return nil
}

func (x *MediaEvent_SdpOffer) GetMidToTrackId() map[string]string {
	if x != nil {
		return x.MidToTrackId
	}
	return nil
}

// Sent when Peer wants to update its track's bitrate
type MediaEvent_TrackBitrates struct {
	state           protoimpl.MessageState       `protogen:"open.v1"`
	TrackId         string                       `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	VariantBitrates []*MediaEvent_VariantBitrate `protobuf:"bytes,2,rep,name=variant_bitrates,json=variantBitrates,proto3" json:"variant_bitrates,omitempty"` // Bitrate of each variant. For non-simulcast tracks use VARIANT_UNSPECIFIED.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MediaEvent_TrackBitrates) Reset() {
	*x = MediaEvent_TrackBitrates{}
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_TrackBitrates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_TrackBitrates) ProtoMessage() {}

func (x *MediaEvent_TrackBitrates) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_TrackBitrates.ProtoReflect.Descriptor instead.
func (*MediaEvent_TrackBitrates) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_peer_peer_proto_rawDescGZIP(), []int{0, 7}
}

func (x *MediaEvent_TrackBitrates) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *MediaEvent_TrackBitrates) GetVariantBitrates() []*MediaEvent_VariantBitrate {
	if x != nil {
		return x.VariantBitrates
	}
	return nil
}

// Sent when client disables one of the track variants
type MediaEvent_DisableTrackVariant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	Variant       media_events.Variant   `protobuf:"varint,2,opt,name=variant,proto3,enum=fishjam.media_events.Variant" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent_DisableTrackVariant) Reset() {
	*x = MediaEvent_DisableTrackVariant{}
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_DisableTrackVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_DisableTrackVariant) ProtoMessage() {}

func (x *MediaEvent_DisableTrackVariant) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_DisableTrackVariant.ProtoReflect.Descriptor instead.
func (*MediaEvent_DisableTrackVariant) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_peer_peer_proto_rawDescGZIP(), []int{0, 8}
}

func (x *MediaEvent_DisableTrackVariant) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *MediaEvent_DisableTrackVariant) GetVariant() media_events.Variant {
	if x != nil {
		return x.Variant
	}
	return media_events.Variant(0)
}

// Sent when client enables one of the track variants
type MediaEvent_EnableTrackVariant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	Variant       media_events.Variant   `protobuf:"varint,2,opt,name=variant,proto3,enum=fishjam.media_events.Variant" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent_EnableTrackVariant) Reset() {
	*x = MediaEvent_EnableTrackVariant{}
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_EnableTrackVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_EnableTrackVariant) ProtoMessage() {}

func (x *MediaEvent_EnableTrackVariant) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_EnableTrackVariant.ProtoReflect.Descriptor instead.
func (*MediaEvent_EnableTrackVariant) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_peer_peer_proto_rawDescGZIP(), []int{0, 9}
}

func (x *MediaEvent_EnableTrackVariant) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *MediaEvent_EnableTrackVariant) GetVariant() media_events.Variant {
	if x != nil {
		return x.Variant
	}
	return media_events.Variant(0)
}

type MediaEvent_SetTargetTrackVariant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	Variant       media_events.Variant   `protobuf:"varint,2,opt,name=variant,proto3,enum=fishjam.media_events.Variant" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent_SetTargetTrackVariant) Reset() {
	*x = MediaEvent_SetTargetTrackVariant{}
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_SetTargetTrackVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_SetTargetTrackVariant) ProtoMessage() {}

func (x *MediaEvent_SetTargetTrackVariant) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_SetTargetTrackVariant.ProtoReflect.Descriptor instead.
func (*MediaEvent_SetTargetTrackVariant) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_peer_peer_proto_rawDescGZIP(), []int{0, 10}
}

func (x *MediaEvent_SetTargetTrackVariant) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *MediaEvent_SetTargetTrackVariant) GetVariant() media_events.Variant {
	if x != nil {
		return x.Variant
	}
	return media_events.Variant(0)
}

type MediaEvent_UnmuteTrack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEvent_UnmuteTrack) Reset() {
	*x = MediaEvent_UnmuteTrack{}
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEvent_UnmuteTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEvent_UnmuteTrack) ProtoMessage() {}

func (x *MediaEvent_UnmuteTrack) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_peer_peer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEvent_UnmuteTrack.ProtoReflect.Descriptor instead.
func (*MediaEvent_UnmuteTrack) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_peer_peer_proto_rawDescGZIP(), []int{0, 11}
}

func (x *MediaEvent_UnmuteTrack) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

var File_fishjam_media_events_peer_peer_proto protoreflect.FileDescriptor

const file_fishjam_media_events_peer_peer_proto_rawDesc = "" +
	"\n" +
	"$fishjam/media_events/peer/peer.proto\x12\x19fishjam.media_events.peer\x1a!fishjam/media_events/shared.proto\"\xfc\x14\n" +
	"\n" +
	"MediaEvent\x12I\n" +
	"\aconnect\x18\x01 \x01(\v2-.fishjam.media_events.peer.MediaEvent.ConnectH\x00R\aconnect\x12R\n" +
	"\n" +
	"disconnect\x18\x02 \x01(\v20.fishjam.media_events.peer.MediaEvent.DisconnectH\x00R\n" +
	"disconnect\x12x\n" +
	"\x18update_endpoint_metadata\x18\x03 \x01(\v2<.fishjam.media_events.peer.MediaEvent.UpdateEndpointMetadataH\x00R\x16updateEndpointMetadata\x12o\n" +
	"\x15update_track_metadata\x18\x04 \x01(\v29.fishjam.media_events.peer.MediaEvent.UpdateTrackMetadataH\x00R\x13updateTrackMetadata\x12h\n" +
	"\x12renegotiate_tracks\x18\x05 \x01(\v27.fishjam.media_events.peer.MediaEvent.RenegotiateTracksH\x00R\x11renegotiateTracks\x12?\n" +
	"\tcandidate\x18\x06 \x01(\v2\x1f.fishjam.media_events.CandidateH\x00R\tcandidate\x12M\n" +
	"\tsdp_offer\x18\a \x01(\v2..fishjam.media_events.peer.MediaEvent.SdpOfferH\x00R\bsdpOffer\x12\\\n" +
	"\x0etrack_bitrates\x18\b \x01(\v23.fishjam.media_events.peer.MediaEvent.TrackBitratesH\x00R\rtrackBitrates\x12l\n" +
	"\x14enable_track_variant\x18\t \x01(\v28.fishjam.media_events.peer.MediaEvent.EnableTrackVariantH\x00R\x12enableTrackVariant\x12o\n" +
	"\x15disable_track_variant\x18\n" +
	" \x01(\v29.fishjam.media_events.peer.MediaEvent.DisableTrackVariantH\x00R\x13disableTrackVariant\x12v\n" +
	"\x18set_target_track_variant\x18\v \x01(\v2;.fishjam.media_events.peer.MediaEvent.SetTargetTrackVariantH\x00R\x15setTargetTrackVariant\x12V\n" +
	"\funmute_track\x18\f \x01(\v21.fishjam.media_events.peer.MediaEvent.UnmuteTrackH\x00R\vunmuteTrack\x1ac\n" +
	"\x0eVariantBitrate\x127\n" +
	"\avariant\x18\x01 \x01(\x0e2\x1d.fishjam.media_events.VariantR\avariant\x12\x18\n" +
	"\abitrate\x18\x02 \x01(\x05R\abitrate\x1a.\n" +
	"\aConnect\x12#\n" +
	"\rmetadata_json\x18\x01 \x01(\tR\fmetadataJson\x1a\f\n" +
	"\n" +
	"Disconnect\x1a=\n" +
	"\x16UpdateEndpointMetadata\x12#\n" +
	"\rmetadata_json\x18\x01 \x01(\tR\fmetadataJson\x1aU\n" +
	"\x13UpdateTrackMetadata\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\x12#\n" +
	"\rmetadata_json\x18\x02 \x01(\tR\fmetadataJson\x1a\x13\n" +
	"\x11RenegotiateTracks\x1a\x89\x05\n" +
	"\bSdpOffer\x12\x10\n" +
	"\x03sdp\x18\x01 \x01(\tR\x03sdp\x12\x83\x01\n" +
	"\x19track_id_to_metadata_json\x18\x02 \x03(\v2I.fishjam.media_events.peer.MediaEvent.SdpOffer.TrackIdToMetadataJsonEntryR\x15trackIdToMetadataJson\x12v\n" +
	"\x14track_id_to_bitrates\x18\x03 \x03(\v2E.fishjam.media_events.peer.MediaEvent.SdpOffer.TrackIdToBitratesEntryR\x11trackIdToBitrates\x12g\n" +
	"\x0fmid_to_track_id\x18\x04 \x03(\v2@.fishjam.media_events.peer.MediaEvent.SdpOffer.MidToTrackIdEntryR\fmidToTrackId\x1aH\n" +
	"\x1aTrackIdToMetadataJsonEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1ay\n" +
	"\x16TrackIdToBitratesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12I\n" +
	"\x05value\x18\x02 \x01(\v23.fishjam.media_events.peer.MediaEvent.TrackBitratesR\x05value:\x028\x01\x1a?\n" +
	"\x11MidToTrackIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\x8b\x01\n" +
	"\rTrackBitrates\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\x12_\n" +
	"\x10variant_bitrates\x18\x02 \x03(\v24.fishjam.media_events.peer.MediaEvent.VariantBitrateR\x0fvariantBitrates\x1ai\n" +
	"\x13DisableTrackVariant\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\x127\n" +
	"\avariant\x18\x02 \x01(\x0e2\x1d.fishjam.media_events.VariantR\avariant\x1ah\n" +
	"\x12EnableTrackVariant\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\x127\n" +
	"\avariant\x18\x02 \x01(\x0e2\x1d.fishjam.media_events.VariantR\avariant\x1ak\n" +
	"\x15SetTargetTrackVariant\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\x127\n" +
	"\avariant\x18\x02 \x01(\x0e2\x1d.fishjam.media_events.VariantR\avariant\x1a(\n" +
	"\vUnmuteTrack\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackIdB\t\n" +
	"\acontentB6Z4conference-to-stream/proto/fishjam/media_events/peerb\x06proto3"

var (
	file_fishjam_media_events_peer_peer_proto_rawDescOnce sync.Once
	file_fishjam_media_events_peer_peer_proto_rawDescData []byte
)

func file_fishjam_media_events_peer_peer_proto_rawDescGZIP() []byte {
	file_fishjam_media_events_peer_peer_proto_rawDescOnce.Do(func() {
		file_fishjam_media_events_peer_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fishjam_media_events_peer_peer_proto_rawDesc), len(file_fishjam_media_events_peer_peer_proto_rawDesc)))
	})
	return file_fishjam_media_events_peer_peer_proto_rawDescData
}

var file_fishjam_media_events_peer_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_fishjam_media_events_peer_peer_proto_goTypes = []any{
	(*MediaEvent)(nil),                        // 0: fishjam.media_events.peer.MediaEvent
	(*MediaEvent_VariantBitrate)(nil),         // 1: fishjam.media_events.peer.MediaEvent.VariantBitrate
	(*MediaEvent_Connect)(nil),                // 2: fishjam.media_events.peer.MediaEvent.Connect
	(*MediaEvent_Disconnect)(nil),             // 3: fishjam.media_events.peer.MediaEvent.Disconnect
	(*MediaEvent_UpdateEndpointMetadata)(nil), // 4: fishjam.media_events.peer.MediaEvent.UpdateEndpointMetadata
	(*MediaEvent_UpdateTrackMetadata)(nil),    // 5: fishjam.media_events.peer.MediaEvent.UpdateTrackMetadata
	(*MediaEvent_RenegotiateTracks)(nil),      // 6: fishjam.media_events.peer.MediaEvent.RenegotiateTracks
	(*MediaEvent_SdpOffer)(nil),               // 7: fishjam.media_events.peer.MediaEvent.SdpOffer
	(*MediaEvent_TrackBitrates)(nil),          // 8: fishjam.media_events.peer.MediaEvent.TrackBitrates
	(*MediaEvent_DisableTrackVariant)(nil),    // 9: fishjam.media_events.peer.MediaEvent.DisableTrackVariant
	(*MediaEvent_EnableTrackVariant)(nil),     // 10: fishjam.media_events.peer.MediaEvent.EnableTrackVariant
	(*MediaEvent_SetTargetTrackVariant)(nil),  // 11: fishjam.media_events.peer.MediaEvent.SetTargetTrackVariant
	(*MediaEvent_UnmuteTrack)(nil),            // 12: fishjam.media_events.peer.MediaEvent.UnmuteTrack
	nil,                                       // 13: fishjam.media_events.peer.MediaEvent.SdpOffer.TrackIdToMetadataJsonEntry
	nil,                                       // 14: fishjam.media_events.peer.MediaEvent.SdpOffer.TrackIdToBitratesEntry
	nil,                                       // 15: fishjam.media_events.peer.MediaEvent.SdpOffer.MidToTrackIdEntry
	(*media_events.Candidate)(nil),            // 16: fishjam.media_events.Candidate
	(media_events.Variant)(0),                 // 17: fishjam.media_events.Variant
}
var file_fishjam_media_events_peer_peer_proto_depIdxs = []int32{
	2,  // 0: fishjam.media_events.peer.MediaEvent.connect:type_name -> fishjam.media_events.peer.MediaEvent.Connect
	3,  // 1: fishjam.media_events.peer.MediaEvent.disconnect:type_name -> fishjam.media_events.peer.MediaEvent.Disconnect
	4,  // 2: fishjam.media_events.peer.MediaEvent.update_endpoint_metadata:type_name -> fishjam.media_events.peer.MediaEvent.UpdateEndpointMetadata
	5,  // 3: fishjam.media_events.peer.MediaEvent.update_track_metadata:type_name -> fishjam.media_events.peer.MediaEvent.UpdateTrackMetadata
	6,  // 4: fishjam.media_events.peer.MediaEvent.renegotiate_tracks:type_name -> fishjam.media_events.peer.MediaEvent.RenegotiateTracks
	16, // 5: fishjam.media_events.peer.MediaEvent.candidate:type_name -> fishjam.media_events.Candidate
	7,  // 6: fishjam.media_events.peer.MediaEvent.sdp_offer:type_name -> fishjam.media_events.peer.MediaEvent.SdpOffer
	8,  // 7: fishjam.media_events.peer.MediaEvent.track_bitrates:type_name -> fishjam.media_events.peer.MediaEvent.TrackBitrates
	10, // 8: fishjam.media_events.peer.MediaEvent.enable_track_variant:type_name -> fishjam.media_events.peer.MediaEvent.EnableTrackVariant
	9,  // 9: fishjam.media_events.peer.MediaEvent.disable_track_variant:type_name -> fishjam.media_events.peer.MediaEvent.DisableTrackVariant
	11, // 10: fishjam.media_events.peer.MediaEvent.set_target_track_variant:type_name -> fishjam.media_events.peer.MediaEvent.SetTargetTrackVariant
	12, // 11: fishjam.media_events.peer.MediaEvent.unmute_track:type_name -> fishjam.media_events.peer.MediaEvent.UnmuteTrack
	17, // 12: fishjam.media_events.peer.MediaEvent.VariantBitrate.variant:type_name -> fishjam.media_events.Variant
	13, // 13: fishjam.media_events.peer.MediaEvent.SdpOffer.track_id_to_metadata_json:type_name -> fishjam.media_events.peer.MediaEvent.SdpOffer.TrackIdToMetadataJsonEntry
	14, // 14: fishjam.media_events.peer.MediaEvent.SdpOffer.track_id_to_bitrates:type_name -> fishjam.media_events.peer.MediaEvent.SdpOffer.TrackIdToBitratesEntry
	15, // 15: fishjam.media_events.peer.MediaEvent.SdpOffer.mid_to_track_id:type_name -> fishjam.media_events.peer.MediaEvent.SdpOffer.MidToTrackIdEntry
	1,  // 16: fishjam.media_events.peer.MediaEvent.TrackBitrates.variant_bitrates:type_name -> fishjam.media_events.peer.MediaEvent.VariantBitrate
	17, // 17: fishjam.media_events.peer.MediaEvent.DisableTrackVariant.variant:type_name -> fishjam.media_events.Variant
	17, // 18: fishjam.media_events.peer.MediaEvent.EnableTrackVariant.variant:type_name -> fishjam.media_events.Variant
	17, // 19: fishjam.media_events.peer.MediaEvent.SetTargetTrackVariant.variant:type_name -> fishjam.media_events.Variant
	8,  // 20: fishjam.media_events.peer.MediaEvent.SdpOffer.TrackIdToBitratesEntry.value:type_name -> fishjam.media_events.peer.MediaEvent.TrackBitrates
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_fishjam_media_events_peer_peer_proto_init() }
func file_fishjam_media_events_peer_peer_proto_init() {
	if File_fishjam_media_events_peer_peer_proto != nil {
		return
	}
	file_fishjam_media_events_peer_peer_proto_msgTypes[0].OneofWrappers = []any{
		(*MediaEvent_Connect_)(nil),
		(*MediaEvent_Disconnect_)(nil),
		(*MediaEvent_UpdateEndpointMetadata_)(nil),
		(*MediaEvent_UpdateTrackMetadata_)(nil),
		(*MediaEvent_RenegotiateTracks_)(nil),
		(*MediaEvent_Candidate)(nil),
		(*MediaEvent_SdpOffer_)(nil),
		(*MediaEvent_TrackBitrates_)(nil),
		(*MediaEvent_EnableTrackVariant_)(nil),
		(*MediaEvent_DisableTrackVariant_)(nil),
		(*MediaEvent_SetTargetTrackVariant_)(nil),
		(*MediaEvent_UnmuteTrack_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fishjam_media_events_peer_peer_proto_rawDesc), len(file_fishjam_media_events_peer_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fishjam_media_events_peer_peer_proto_goTypes,
		DependencyIndexes: file_fishjam_media_events_peer_peer_proto_depIdxs,
		MessageInfos:      file_fishjam_media_events_peer_peer_proto_msgTypes,
	}.Build()
	File_fishjam_media_events_peer_peer_proto = out.File
	file_fishjam_media_events_peer_peer_proto_goTypes = nil
	file_fishjam_media_events_peer_peer_proto_depIdxs = nil
}
