// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: fishjam/notifications/shared.proto

package notifications

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defines types of tracks being published by peers and component
type TrackType int32

const (
	TrackType_TRACK_TYPE_UNSPECIFIED TrackType = 0
	TrackType_TRACK_TYPE_VIDEO       TrackType = 1
	TrackType_TRACK_TYPE_AUDIO       TrackType = 2
)

// Enum value maps for TrackType.
var (
	TrackType_name = map[int32]string{
		0: "TRACK_TYPE_UNSPECIFIED",
		1: "TRACK_TYPE_VIDEO",
		2: "TRACK_TYPE_AUDIO",
	}
	TrackType_value = map[string]int32{
		"TRACK_TYPE_UNSPECIFIED": 0,
		"TRACK_TYPE_VIDEO":       1,
		"TRACK_TYPE_AUDIO":       2,
	}
)

func (x TrackType) Enum() *TrackType {
	p := new(TrackType)
	*p = x
	return p
}

func (x TrackType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrackType) Descriptor() protoreflect.EnumDescriptor {
	return file_fishjam_notifications_shared_proto_enumTypes[0].Descriptor()
}

func (TrackType) Type() protoreflect.EnumType {
	return &file_fishjam_notifications_shared_proto_enumTypes[0]
}

func (x TrackType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrackType.Descriptor instead.
func (TrackType) EnumDescriptor() ([]byte, []int) {
	return file_fishjam_notifications_shared_proto_rawDescGZIP(), []int{0}
}

type TrackEncoding int32

const (
	TrackEncoding_TRACK_ENCODING_UNSPECIFIED TrackEncoding = 0
	TrackEncoding_TRACK_ENCODING_PCM16       TrackEncoding = 1
	TrackEncoding_TRACK_ENCODING_OPUS        TrackEncoding = 2
)

// Enum value maps for TrackEncoding.
var (
	TrackEncoding_name = map[int32]string{
		0: "TRACK_ENCODING_UNSPECIFIED",
		1: "TRACK_ENCODING_PCM16",
		2: "TRACK_ENCODING_OPUS",
	}
	TrackEncoding_value = map[string]int32{
		"TRACK_ENCODING_UNSPECIFIED": 0,
		"TRACK_ENCODING_PCM16":       1,
		"TRACK_ENCODING_OPUS":        2,
	}
)

func (x TrackEncoding) Enum() *TrackEncoding {
	p := new(TrackEncoding)
	*p = x
	return p
}

func (x TrackEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrackEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_fishjam_notifications_shared_proto_enumTypes[1].Descriptor()
}

func (TrackEncoding) Type() protoreflect.EnumType {
	return &file_fishjam_notifications_shared_proto_enumTypes[1]
}

func (x TrackEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrackEncoding.Descriptor instead.
func (TrackEncoding) EnumDescriptor() ([]byte, []int) {
	return file_fishjam_notifications_shared_proto_rawDescGZIP(), []int{1}
}

// Describes a media track
type Track struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          TrackType              `protobuf:"varint,2,opt,name=type,proto3,enum=fishjam.notifications.TrackType" json:"type,omitempty"`
	Metadata      string                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Track) Reset() {
	*x = Track{}
	mi := &file_fishjam_notifications_shared_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Track) ProtoMessage() {}

func (x *Track) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_notifications_shared_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Track.ProtoReflect.Descriptor instead.
func (*Track) Descriptor() ([]byte, []int) {
	return file_fishjam_notifications_shared_proto_rawDescGZIP(), []int{0}
}

func (x *Track) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Track) GetType() TrackType {
	if x != nil {
		return x.Type
	}
	return TrackType_TRACK_TYPE_UNSPECIFIED
}

func (x *Track) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

var File_fishjam_notifications_shared_proto protoreflect.FileDescriptor

const file_fishjam_notifications_shared_proto_rawDesc = "" +
	"\n" +
	"\"fishjam/notifications/shared.proto\x12\x15fishjam.notifications\"i\n" +
	"\x05Track\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\x04type\x18\x02 \x01(\x0e2 .fishjam.notifications.TrackTypeR\x04type\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata*S\n" +
	"\tTrackType\x12\x1a\n" +
	"\x16TRACK_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TRACK_TYPE_VIDEO\x10\x01\x12\x14\n" +
	"\x10TRACK_TYPE_AUDIO\x10\x02*b\n" +
	"\rTrackEncoding\x12\x1e\n" +
	"\x1aTRACK_ENCODING_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TRACK_ENCODING_PCM16\x10\x01\x12\x17\n" +
	"\x13TRACK_ENCODING_OPUS\x10\x02B2Z0conference-to-stream/proto/fishjam/notificationsb\x06proto3"

var (
	file_fishjam_notifications_shared_proto_rawDescOnce sync.Once
	file_fishjam_notifications_shared_proto_rawDescData []byte
)

func file_fishjam_notifications_shared_proto_rawDescGZIP() []byte {
	file_fishjam_notifications_shared_proto_rawDescOnce.Do(func() {
		file_fishjam_notifications_shared_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fishjam_notifications_shared_proto_rawDesc), len(file_fishjam_notifications_shared_proto_rawDesc)))
	})
	return file_fishjam_notifications_shared_proto_rawDescData
}

var file_fishjam_notifications_shared_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_fishjam_notifications_shared_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_fishjam_notifications_shared_proto_goTypes = []any{
	(TrackType)(0),     // 0: fishjam.notifications.TrackType
	(TrackEncoding)(0), // 1: fishjam.notifications.TrackEncoding
	(*Track)(nil),      // 2: fishjam.notifications.Track
}
var file_fishjam_notifications_shared_proto_depIdxs = []int32{
	0, // 0: fishjam.notifications.Track.type:type_name -> fishjam.notifications.TrackType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fishjam_notifications_shared_proto_init() }
func file_fishjam_notifications_shared_proto_init() {
	if File_fishjam_notifications_shared_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fishjam_notifications_shared_proto_rawDesc), len(file_fishjam_notifications_shared_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fishjam_notifications_shared_proto_goTypes,
		DependencyIndexes: file_fishjam_notifications_shared_proto_depIdxs,
		EnumInfos:         file_fishjam_notifications_shared_proto_enumTypes,
		MessageInfos:      file_fishjam_notifications_shared_proto_msgTypes,
	}.Build()
	File_fishjam_notifications_shared_proto = out.File
	file_fishjam_notifications_shared_proto_goTypes = nil
	file_fishjam_notifications_shared_proto_depIdxs = nil
}
