nodeLinker: node-modules

packageExtensions:
  "@moq/hang@0.2.10":
    dependencies:
      "@svta/cml-utils": "1.5.0"
  "@moq/loc@0.1.1":
    dependencies:
      zod: "^4.4.3"
  "@moq/publish@0.2.15":
    dependencies:
      zod: "^4.4.3"
  "@moq/watch@0.2.17":
    dependencies:
      zod: "^4.4.3"
