// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: fishjam/media_events/shared.proto

package media_events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Variant int32

const (
	Variant_VARIANT_UNSPECIFIED Variant = 0
	Variant_VARIANT_LOW         Variant = 1
	Variant_VARIANT_MEDIUM      Variant = 2
	Variant_VARIANT_HIGH        Variant = 3
)

// Enum value maps for Variant.
var (
	Variant_name = map[int32]string{
		0: "VARIANT_UNSPECIFIED",
		1: "VARIANT_LOW",
		2: "VARIANT_MEDIUM",
		3: "VARIANT_HIGH",
	}
	Variant_value = map[string]int32{
		"VARIANT_UNSPECIFIED": 0,
		"VARIANT_LOW":         1,
		"VARIANT_MEDIUM":      2,
		"VARIANT_HIGH":        3,
	}
)

func (x Variant) Enum() *Variant {
	p := new(Variant)
	*p = x
	return p
}

func (x Variant) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Variant) Descriptor() protoreflect.EnumDescriptor {
	return file_fishjam_media_events_shared_proto_enumTypes[0].Descriptor()
}

func (Variant) Type() protoreflect.EnumType {
	return &file_fishjam_media_events_shared_proto_enumTypes[0]
}

func (x Variant) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Variant.Descriptor instead.
func (Variant) EnumDescriptor() ([]byte, []int) {
	return file_fishjam_media_events_shared_proto_rawDescGZIP(), []int{0}
}

// Contains information about an ICE candidate which will be sent to the peer/server
type Candidate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Candidate        string                 `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	SdpMLineIndex    int32                  `protobuf:"varint,2,opt,name=sdp_m_line_index,json=sdpMLineIndex,proto3" json:"sdp_m_line_index,omitempty"`
	SdpMid           string                 `protobuf:"bytes,3,opt,name=sdp_mid,json=sdpMid,proto3" json:"sdp_mid,omitempty"`
	UsernameFragment string                 `protobuf:"bytes,4,opt,name=username_fragment,json=usernameFragment,proto3" json:"username_fragment,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_fishjam_media_events_shared_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_shared_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_shared_proto_rawDescGZIP(), []int{0}
}

func (x *Candidate) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *Candidate) GetSdpMLineIndex() int32 {
	if x != nil {
		return x.SdpMLineIndex
	}
	return 0
}

func (x *Candidate) GetSdpMid() string {
	if x != nil {
		return x.SdpMid
	}
	return ""
}

func (x *Candidate) GetUsernameFragment() string {
	if x != nil {
		return x.UsernameFragment
	}
	return ""
}

type ChannelMessageBinaryPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelMessageBinaryPayload) Reset() {
	*x = ChannelMessageBinaryPayload{}
	mi := &file_fishjam_media_events_shared_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelMessageBinaryPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelMessageBinaryPayload) ProtoMessage() {}

func (x *ChannelMessageBinaryPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_shared_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelMessageBinaryPayload.ProtoReflect.Descriptor instead.
func (*ChannelMessageBinaryPayload) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_shared_proto_rawDescGZIP(), []int{1}
}

func (x *ChannelMessageBinaryPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ChannelMessage struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Source       string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destinations []string               `protobuf:"bytes,2,rep,name=destinations,proto3" json:"destinations,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ChannelMessage_Binary
	Payload       isChannelMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelMessage) Reset() {
	*x = ChannelMessage{}
	mi := &file_fishjam_media_events_shared_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelMessage) ProtoMessage() {}

func (x *ChannelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_media_events_shared_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelMessage.ProtoReflect.Descriptor instead.
func (*ChannelMessage) Descriptor() ([]byte, []int) {
	return file_fishjam_media_events_shared_proto_rawDescGZIP(), []int{2}
}

func (x *ChannelMessage) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ChannelMessage) GetDestinations() []string {
	if x != nil {
		return x.Destinations
	}
	return nil
}

func (x *ChannelMessage) GetPayload() isChannelMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChannelMessage) GetBinary() *ChannelMessageBinaryPayload {
	if x != nil {
		if x, ok := x.Payload.(*ChannelMessage_Binary); ok {
			return x.Binary
		}
	}
	return nil
}

type isChannelMessage_Payload interface {
	isChannelMessage_Payload()
}

type ChannelMessage_Binary struct {
	Binary *ChannelMessageBinaryPayload `protobuf:"bytes,3,opt,name=binary,proto3,oneof"`
}

func (*ChannelMessage_Binary) isChannelMessage_Payload() {}

var File_fishjam_media_events_shared_proto protoreflect.FileDescriptor

const file_fishjam_media_events_shared_proto_rawDesc = "" +
	"\n" +
	"!fishjam/media_events/shared.proto\x12\x14fishjam.media_events\"\x98\x01\n" +
	"\tCandidate\x12\x1c\n" +
	"\tcandidate\x18\x01 \x01(\tR\tcandidate\x12'\n" +
	"\x10sdp_m_line_index\x18\x02 \x01(\x05R\rsdpMLineIndex\x12\x17\n" +
	"\asdp_mid\x18\x03 \x01(\tR\x06sdpMid\x12+\n" +
	"\x11username_fragment\x18\x04 \x01(\tR\x10usernameFragment\"1\n" +
	"\x1bChannelMessageBinaryPayload\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xa4\x01\n" +
	"\x0eChannelMessage\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\"\n" +
	"\fdestinations\x18\x02 \x03(\tR\fdestinations\x12K\n" +
	"\x06binary\x18\x03 \x01(\v21.fishjam.media_events.ChannelMessageBinaryPayloadH\x00R\x06binaryB\t\n" +
	"\apayload*Y\n" +
	"\aVariant\x12\x17\n" +
	"\x13VARIANT_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vVARIANT_LOW\x10\x01\x12\x12\n" +
	"\x0eVARIANT_MEDIUM\x10\x02\x12\x10\n" +
	"\fVARIANT_HIGH\x10\x03B1Z/conference-to-stream/proto/fishjam/media_eventsb\x06proto3"

var (
	file_fishjam_media_events_shared_proto_rawDescOnce sync.Once
	file_fishjam_media_events_shared_proto_rawDescData []byte
)

func file_fishjam_media_events_shared_proto_rawDescGZIP() []byte {
	file_fishjam_media_events_shared_proto_rawDescOnce.Do(func() {
		file_fishjam_media_events_shared_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fishjam_media_events_shared_proto_rawDesc), len(file_fishjam_media_events_shared_proto_rawDesc)))
	})
	return file_fishjam_media_events_shared_proto_rawDescData
}

var file_fishjam_media_events_shared_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fishjam_media_events_shared_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_fishjam_media_events_shared_proto_goTypes = []any{
	(Variant)(0),                        // 0: fishjam.media_events.Variant
	(*Candidate)(nil),                   // 1: fishjam.media_events.Candidate
	(*ChannelMessageBinaryPayload)(nil), // 2: fishjam.media_events.ChannelMessageBinaryPayload
	(*ChannelMessage)(nil),              // 3: fishjam.media_events.ChannelMessage
}
var file_fishjam_media_events_shared_proto_depIdxs = []int32{
	2, // 0: fishjam.media_events.ChannelMessage.binary:type_name -> fishjam.media_events.ChannelMessageBinaryPayload
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fishjam_media_events_shared_proto_init() }
func file_fishjam_media_events_shared_proto_init() {
	if File_fishjam_media_events_shared_proto != nil {
		return
	}
	file_fishjam_media_events_shared_proto_msgTypes[2].OneofWrappers = []any{
		(*ChannelMessage_Binary)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fishjam_media_events_shared_proto_rawDesc), len(file_fishjam_media_events_shared_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fishjam_media_events_shared_proto_goTypes,
		DependencyIndexes: file_fishjam_media_events_shared_proto_depIdxs,
		EnumInfos:         file_fishjam_media_events_shared_proto_enumTypes,
		MessageInfos:      file_fishjam_media_events_shared_proto_msgTypes,
	}.Build()
	File_fishjam_media_events_shared_proto = out.File
	file_fishjam_media_events_shared_proto_goTypes = nil
	file_fishjam_media_events_shared_proto_depIdxs = nil
}
