packageExtensions:
  "@moq/loc@*":
    dependencies:
      zod: "^4.0.0"
  "@moq/publish@*":
    dependencies:
      "@moq/json": "^0.3.2"
      zod: "^4.0.0"
  "@moq/watch@*":
    dependencies:
      "@moq/json": "^0.3.2"
      zod: "^4.0.0"
