// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: fishjam/agent_notifications.proto

package fishjam

import (
	notifications "conference-to-stream/proto/fishjam/notifications"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defines any type of message passed from agent peer to Fishjam
type AgentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*AgentRequest_AuthRequest_
	//	*AgentRequest_AddTrack_
	//	*AgentRequest_RemoveTrack_
	//	*AgentRequest_TrackData_
	//	*AgentRequest_InterruptTrack_
	//	*AgentRequest_CaptureImage_
	Content       isAgentRequest_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRequest) Reset() {
	*x = AgentRequest{}
	mi := &file_fishjam_agent_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest) ProtoMessage() {}

func (x *AgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_agent_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest.ProtoReflect.Descriptor instead.
func (*AgentRequest) Descriptor() ([]byte, []int) {
	return file_fishjam_agent_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRequest) GetContent() isAgentRequest_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *AgentRequest) GetAuthRequest() *AgentRequest_AuthRequest {
	if x != nil {
		if x, ok := x.Content.(*AgentRequest_AuthRequest_); ok {
			return x.AuthRequest
		}
	}
	return nil
}

func (x *AgentRequest) GetAddTrack() *AgentRequest_AddTrack {
	if x != nil {
		if x, ok := x.Content.(*AgentRequest_AddTrack_); ok {
			return x.AddTrack
		}
	}
	return nil
}

func (x *AgentRequest) GetRemoveTrack() *AgentRequest_RemoveTrack {
	if x != nil {
		if x, ok := x.Content.(*AgentRequest_RemoveTrack_); ok {
			return x.RemoveTrack
		}
	}
	return nil
}

func (x *AgentRequest) GetTrackData() *AgentRequest_TrackData {
	if x != nil {
		if x, ok := x.Content.(*AgentRequest_TrackData_); ok {
			return x.TrackData
		}
	}
	return nil
}

func (x *AgentRequest) GetInterruptTrack() *AgentRequest_InterruptTrack {
	if x != nil {
		if x, ok := x.Content.(*AgentRequest_InterruptTrack_); ok {
			return x.InterruptTrack
		}
	}
	return nil
}

func (x *AgentRequest) GetCaptureImage() *AgentRequest_CaptureImage {
	if x != nil {
		if x, ok := x.Content.(*AgentRequest_CaptureImage_); ok {
			return x.CaptureImage
		}
	}
	return nil
}

type isAgentRequest_Content interface {
	isAgentRequest_Content()
}

type AgentRequest_AuthRequest_ struct {
	AuthRequest *AgentRequest_AuthRequest `protobuf:"bytes,1,opt,name=auth_request,json=authRequest,proto3,oneof"`
}

type AgentRequest_AddTrack_ struct {
	AddTrack *AgentRequest_AddTrack `protobuf:"bytes,2,opt,name=add_track,json=addTrack,proto3,oneof"`
}

type AgentRequest_RemoveTrack_ struct {
	RemoveTrack *AgentRequest_RemoveTrack `protobuf:"bytes,3,opt,name=remove_track,json=removeTrack,proto3,oneof"`
}

type AgentRequest_TrackData_ struct {
	TrackData *AgentRequest_TrackData `protobuf:"bytes,4,opt,name=track_data,json=trackData,proto3,oneof"`
}

type AgentRequest_InterruptTrack_ struct {
	InterruptTrack *AgentRequest_InterruptTrack `protobuf:"bytes,5,opt,name=interrupt_track,json=interruptTrack,proto3,oneof"`
}

type AgentRequest_CaptureImage_ struct {
	CaptureImage *AgentRequest_CaptureImage `protobuf:"bytes,6,opt,name=capture_image,json=captureImage,proto3,oneof"`
}

func (*AgentRequest_AuthRequest_) isAgentRequest_Content() {}

func (*AgentRequest_AddTrack_) isAgentRequest_Content() {}

func (*AgentRequest_RemoveTrack_) isAgentRequest_Content() {}

func (*AgentRequest_TrackData_) isAgentRequest_Content() {}

func (*AgentRequest_InterruptTrack_) isAgentRequest_Content() {}

func (*AgentRequest_CaptureImage_) isAgentRequest_Content() {}

// Defines any type of message passed from Fishjam to agent peer
type AgentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*AgentResponse_Authenticated_
	//	*AgentResponse_TrackData_
	//	*AgentResponse_TrackImage_
	Content       isAgentResponse_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResponse) Reset() {
	*x = AgentResponse{}
	mi := &file_fishjam_agent_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResponse) ProtoMessage() {}

func (x *AgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_agent_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResponse.ProtoReflect.Descriptor instead.
func (*AgentResponse) Descriptor() ([]byte, []int) {
	return file_fishjam_agent_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *AgentResponse) GetContent() isAgentResponse_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *AgentResponse) GetAuthenticated() *AgentResponse_Authenticated {
	if x != nil {
		if x, ok := x.Content.(*AgentResponse_Authenticated_); ok {
			return x.Authenticated
		}
	}
	return nil
}

func (x *AgentResponse) GetTrackData() *AgentResponse_TrackData {
	if x != nil {
		if x, ok := x.Content.(*AgentResponse_TrackData_); ok {
			return x.TrackData
		}
	}
	return nil
}

func (x *AgentResponse) GetTrackImage() *AgentResponse_TrackImage {
	if x != nil {
		if x, ok := x.Content.(*AgentResponse_TrackImage_); ok {
			return x.TrackImage
		}
	}
	return nil
}

type isAgentResponse_Content interface {
	isAgentResponse_Content()
}

type AgentResponse_Authenticated_ struct {
	Authenticated *AgentResponse_Authenticated `protobuf:"bytes,1,opt,name=authenticated,proto3,oneof"`
}

type AgentResponse_TrackData_ struct {
	TrackData *AgentResponse_TrackData `protobuf:"bytes,2,opt,name=track_data,json=trackData,proto3,oneof"`
}

type AgentResponse_TrackImage_ struct {
	TrackImage *AgentResponse_TrackImage `protobuf:"bytes,3,opt,name=track_image,json=trackImage,proto3,oneof"`
}

func (*AgentResponse_Authenticated_) isAgentResponse_Content() {}

func (*AgentResponse_TrackData_) isAgentResponse_Content() {}

func (*AgentResponse_TrackImage_) isAgentResponse_Content() {}

// Request sent by agent, to authenticate to Fishjam server
type AgentRequest_AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRequest_AuthRequest) Reset() {
	*x = AgentRequest_AuthRequest{}
	mi := &file_fishjam_agent_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest_AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest_AuthRequest) ProtoMessage() {}

func (x *AgentRequest_AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_agent_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest_AuthRequest.ProtoReflect.Descriptor instead.
func (*AgentRequest_AuthRequest) Descriptor() ([]byte, []int) {
	return file_fishjam_agent_notifications_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AgentRequest_AuthRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Request to add a track of the specified type
type AgentRequest_AddTrack struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specification of the track to be added
	Track *notifications.Track `protobuf:"bytes,1,opt,name=track,proto3" json:"track,omitempty"`
	// Parameters of the input data stream
	CodecParams   *AgentRequest_AddTrack_CodecParameters `protobuf:"bytes,2,opt,name=codec_params,json=codecParams,proto3" json:"codec_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRequest_AddTrack) Reset() {
	*x = AgentRequest_AddTrack{}
	mi := &file_fishjam_agent_notifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest_AddTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest_AddTrack) ProtoMessage() {}

func (x *AgentRequest_AddTrack) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_agent_notifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest_AddTrack.ProtoReflect.Descriptor instead.
func (*AgentRequest_AddTrack) Descriptor() ([]byte, []int) {
	return file_fishjam_agent_notifications_proto_rawDescGZIP(), []int{0, 1}
}

func (x *AgentRequest_AddTrack) GetTrack() *notifications.Track {
	if x != nil {
		return x.Track
	}
	return nil
}

func (x *AgentRequest_AddTrack) GetCodecParams() *AgentRequest_AddTrack_CodecParameters {
	if x != nil {
		return x.CodecParams
	}
	return nil
}

// Removes the given track
type AgentRequest_RemoveTrack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRequest_RemoveTrack) Reset() {
	*x = AgentRequest_RemoveTrack{}
	mi := &file_fishjam_agent_notifications_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest_RemoveTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest_RemoveTrack) ProtoMessage() {}

func (x *AgentRequest_RemoveTrack) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_agent_notifications_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest_RemoveTrack.ProtoReflect.Descriptor instead.
func (*AgentRequest_RemoveTrack) Descriptor() ([]byte, []int) {
	return file_fishjam_agent_notifications_proto_rawDescGZIP(), []int{0, 2}
}

func (x *AgentRequest_RemoveTrack) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

// Notification containing a chunk of an agent's track's data stream
type AgentRequest_TrackData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRequest_TrackData) Reset() {
	*x = AgentRequest_TrackData{}
	mi := &file_fishjam_agent_notifications_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest_TrackData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest_TrackData) ProtoMessage() {}

func (x *AgentRequest_TrackData) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_agent_notifications_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest_TrackData.ProtoReflect.Descriptor instead.
func (*AgentRequest_TrackData) Descriptor() ([]byte, []int) {
	return file_fishjam_agent_notifications_proto_rawDescGZIP(), []int{0, 3}
}

func (x *AgentRequest_TrackData) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *AgentRequest_TrackData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Interrupts an agent's outgoing track, preventing already queued audio from being played
type AgentRequest_InterruptTrack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRequest_InterruptTrack) Reset() {
	*x = AgentRequest_InterruptTrack{}
	mi := &file_fishjam_agent_notifications_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest_InterruptTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest_InterruptTrack) ProtoMessage() {}

func (x *AgentRequest_InterruptTrack) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_agent_notifications_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest_InterruptTrack.ProtoReflect.Descriptor instead.
func (*AgentRequest_InterruptTrack) Descriptor() ([]byte, []int) {
	return file_fishjam_agent_notifications_proto_rawDescGZIP(), []int{0, 4}
}

func (x *AgentRequest_InterruptTrack) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

type AgentRequest_CaptureImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRequest_CaptureImage) Reset() {
	*x = AgentRequest_CaptureImage{}
	mi := &file_fishjam_agent_notifications_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest_CaptureImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest_CaptureImage) ProtoMessage() {}

func (x *AgentRequest_CaptureImage) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_agent_notifications_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest_CaptureImage.ProtoReflect.Descriptor instead.
func (*AgentRequest_CaptureImage) Descriptor() ([]byte, []int) {
	return file_fishjam_agent_notifications_proto_rawDescGZIP(), []int{0, 5}
}

func (x *AgentRequest_CaptureImage) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

type AgentRequest_AddTrack_CodecParameters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The format of the input stream, defaults to pcm16
	Encoding notifications.TrackEncoding `protobuf:"varint,1,opt,name=encoding,proto3,enum=fishjam.notifications.TrackEncoding" json:"encoding,omitempty"`
	// The sample rate of the input stream, may be omitted for opus
	SampleRate uint32 `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	// The number of channels. 1 means mono, 2 means stereo
	Channels      uint32 `protobuf:"varint,3,opt,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRequest_AddTrack_CodecParameters) Reset() {
	*x = AgentRequest_AddTrack_CodecParameters{}
	mi := &file_fishjam_agent_notifications_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest_AddTrack_CodecParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest_AddTrack_CodecParameters) ProtoMessage() {}

func (x *AgentRequest_AddTrack_CodecParameters) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_agent_notifications_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest_AddTrack_CodecParameters.ProtoReflect.Descriptor instead.
func (*AgentRequest_AddTrack_CodecParameters) Descriptor() ([]byte, []int) {
	return file_fishjam_agent_notifications_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *AgentRequest_AddTrack_CodecParameters) GetEncoding() notifications.TrackEncoding {
	if x != nil {
		return x.Encoding
	}
	return notifications.TrackEncoding(0)
}

func (x *AgentRequest_AddTrack_CodecParameters) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AgentRequest_AddTrack_CodecParameters) GetChannels() uint32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

// Response confirming successful authentication
type AgentResponse_Authenticated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResponse_Authenticated) Reset() {
	*x = AgentResponse_Authenticated{}
	mi := &file_fishjam_agent_notifications_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResponse_Authenticated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResponse_Authenticated) ProtoMessage() {}

func (x *AgentResponse_Authenticated) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_agent_notifications_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResponse_Authenticated.ProtoReflect.Descriptor instead.
func (*AgentResponse_Authenticated) Descriptor() ([]byte, []int) {
	return file_fishjam_agent_notifications_proto_rawDescGZIP(), []int{1, 0}
}

// Notification containing a chunk of a track's data stream
type AgentResponse_TrackData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Track         *notifications.Track   `protobuf:"bytes,2,opt,name=track,proto3" json:"track,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResponse_TrackData) Reset() {
	*x = AgentResponse_TrackData{}
	mi := &file_fishjam_agent_notifications_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResponse_TrackData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResponse_TrackData) ProtoMessage() {}

func (x *AgentResponse_TrackData) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_agent_notifications_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResponse_TrackData.ProtoReflect.Descriptor instead.
func (*AgentResponse_TrackData) Descriptor() ([]byte, []int) {
	return file_fishjam_agent_notifications_proto_rawDescGZIP(), []int{1, 1}
}

func (x *AgentResponse_TrackData) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *AgentResponse_TrackData) GetTrack() *notifications.Track {
	if x != nil {
		return x.Track
	}
	return nil
}

func (x *AgentResponse_TrackData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AgentResponse_TrackImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResponse_TrackImage) Reset() {
	*x = AgentResponse_TrackImage{}
	mi := &file_fishjam_agent_notifications_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResponse_TrackImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResponse_TrackImage) ProtoMessage() {}

func (x *AgentResponse_TrackImage) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_agent_notifications_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResponse_TrackImage.ProtoReflect.Descriptor instead.
func (*AgentResponse_TrackImage) Descriptor() ([]byte, []int) {
	return file_fishjam_agent_notifications_proto_rawDescGZIP(), []int{1, 2}
}

func (x *AgentResponse_TrackImage) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *AgentResponse_TrackImage) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *AgentResponse_TrackImage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_fishjam_agent_notifications_proto protoreflect.FileDescriptor

const file_fishjam_agent_notifications_proto_rawDesc = "" +
	"\n" +
	"!fishjam/agent_notifications.proto\x12\afishjam\x1a\"fishjam/notifications/shared.proto\"\xd0\a\n" +
	"\fAgentRequest\x12F\n" +
	"\fauth_request\x18\x01 \x01(\v2!.fishjam.AgentRequest.AuthRequestH\x00R\vauthRequest\x12=\n" +
	"\tadd_track\x18\x02 \x01(\v2\x1e.fishjam.AgentRequest.AddTrackH\x00R\baddTrack\x12F\n" +
	"\fremove_track\x18\x03 \x01(\v2!.fishjam.AgentRequest.RemoveTrackH\x00R\vremoveTrack\x12@\n" +
	"\n" +
	"track_data\x18\x04 \x01(\v2\x1f.fishjam.AgentRequest.TrackDataH\x00R\ttrackData\x12O\n" +
	"\x0finterrupt_track\x18\x05 \x01(\v2$.fishjam.AgentRequest.InterruptTrackH\x00R\x0einterruptTrack\x12I\n" +
	"\rcapture_image\x18\x06 \x01(\v2\".fishjam.AgentRequest.CaptureImageH\x00R\fcaptureImage\x1a#\n" +
	"\vAuthRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x1a\xa4\x02\n" +
	"\bAddTrack\x122\n" +
	"\x05track\x18\x01 \x01(\v2\x1c.fishjam.notifications.TrackR\x05track\x12Q\n" +
	"\fcodec_params\x18\x02 \x01(\v2..fishjam.AgentRequest.AddTrack.CodecParametersR\vcodecParams\x1a\x90\x01\n" +
	"\x0fCodecParameters\x12@\n" +
	"\bencoding\x18\x01 \x01(\x0e2$.fishjam.notifications.TrackEncodingR\bencoding\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\rR\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x03 \x01(\rR\bchannels\x1a(\n" +
	"\vRemoveTrack\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\x1a:\n" +
	"\tTrackData\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x1a+\n" +
	"\x0eInterruptTrack\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\x1a)\n" +
	"\fCaptureImage\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackIdB\t\n" +
	"\acontent\"\xd0\x03\n" +
	"\rAgentResponse\x12L\n" +
	"\rauthenticated\x18\x01 \x01(\v2$.fishjam.AgentResponse.AuthenticatedH\x00R\rauthenticated\x12A\n" +
	"\n" +
	"track_data\x18\x02 \x01(\v2 .fishjam.AgentResponse.TrackDataH\x00R\ttrackData\x12D\n" +
	"\vtrack_image\x18\x03 \x01(\v2!.fishjam.AgentResponse.TrackImageH\x00R\n" +
	"trackImage\x1a\x0f\n" +
	"\rAuthenticated\x1al\n" +
	"\tTrackData\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x122\n" +
	"\x05track\x18\x02 \x01(\v2\x1c.fishjam.notifications.TrackR\x05track\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x1a^\n" +
	"\n" +
	"TrackImage\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04dataB\t\n" +
	"\acontentB$Z\"conference-to-stream/proto/fishjamb\x06proto3"

var (
	file_fishjam_agent_notifications_proto_rawDescOnce sync.Once
	file_fishjam_agent_notifications_proto_rawDescData []byte
)

func file_fishjam_agent_notifications_proto_rawDescGZIP() []byte {
	file_fishjam_agent_notifications_proto_rawDescOnce.Do(func() {
		file_fishjam_agent_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fishjam_agent_notifications_proto_rawDesc), len(file_fishjam_agent_notifications_proto_rawDesc)))
	})
	return file_fishjam_agent_notifications_proto_rawDescData
}

var file_fishjam_agent_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_fishjam_agent_notifications_proto_goTypes = []any{
	(*AgentRequest)(nil),                          // 0: fishjam.AgentRequest
	(*AgentResponse)(nil),                         // 1: fishjam.AgentResponse
	(*AgentRequest_AuthRequest)(nil),              // 2: fishjam.AgentRequest.AuthRequest
	(*AgentRequest_AddTrack)(nil),                 // 3: fishjam.AgentRequest.AddTrack
	(*AgentRequest_RemoveTrack)(nil),              // 4: fishjam.AgentRequest.RemoveTrack
	(*AgentRequest_TrackData)(nil),                // 5: fishjam.AgentRequest.TrackData
	(*AgentRequest_InterruptTrack)(nil),           // 6: fishjam.AgentRequest.InterruptTrack
	(*AgentRequest_CaptureImage)(nil),             // 7: fishjam.AgentRequest.CaptureImage
	(*AgentRequest_AddTrack_CodecParameters)(nil), // 8: fishjam.AgentRequest.AddTrack.CodecParameters
	(*AgentResponse_Authenticated)(nil),           // 9: fishjam.AgentResponse.Authenticated
	(*AgentResponse_TrackData)(nil),               // 10: fishjam.AgentResponse.TrackData
	(*AgentResponse_TrackImage)(nil),              // 11: fishjam.AgentResponse.TrackImage
	(*notifications.Track)(nil),                   // 12: fishjam.notifications.Track
	(notifications.TrackEncoding)(0),              // 13: fishjam.notifications.TrackEncoding
}
var file_fishjam_agent_notifications_proto_depIdxs = []int32{
	2,  // 0: fishjam.AgentRequest.auth_request:type_name -> fishjam.AgentRequest.AuthRequest
	3,  // 1: fishjam.AgentRequest.add_track:type_name -> fishjam.AgentRequest.AddTrack
	4,  // 2: fishjam.AgentRequest.remove_track:type_name -> fishjam.AgentRequest.RemoveTrack
	5,  // 3: fishjam.AgentRequest.track_data:type_name -> fishjam.AgentRequest.TrackData
	6,  // 4: fishjam.AgentRequest.interrupt_track:type_name -> fishjam.AgentRequest.InterruptTrack
	7,  // 5: fishjam.AgentRequest.capture_image:type_name -> fishjam.AgentRequest.CaptureImage
	9,  // 6: fishjam.AgentResponse.authenticated:type_name -> fishjam.AgentResponse.Authenticated
	10, // 7: fishjam.AgentResponse.track_data:type_name -> fishjam.AgentResponse.TrackData
	11, // 8: fishjam.AgentResponse.track_image:type_name -> fishjam.AgentResponse.TrackImage
	12, // 9: fishjam.AgentRequest.AddTrack.track:type_name -> fishjam.notifications.Track
	8,  // 10: fishjam.AgentRequest.AddTrack.codec_params:type_name -> fishjam.AgentRequest.AddTrack.CodecParameters
	13, // 11: fishjam.AgentRequest.AddTrack.CodecParameters.encoding:type_name -> fishjam.notifications.TrackEncoding
	12, // 12: fishjam.AgentResponse.TrackData.track:type_name -> fishjam.notifications.Track
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_fishjam_agent_notifications_proto_init() }
func file_fishjam_agent_notifications_proto_init() {
	if File_fishjam_agent_notifications_proto != nil {
		return
	}
	file_fishjam_agent_notifications_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentRequest_AuthRequest_)(nil),
		(*AgentRequest_AddTrack_)(nil),
		(*AgentRequest_RemoveTrack_)(nil),
		(*AgentRequest_TrackData_)(nil),
		(*AgentRequest_InterruptTrack_)(nil),
		(*AgentRequest_CaptureImage_)(nil),
	}
	file_fishjam_agent_notifications_proto_msgTypes[1].OneofWrappers = []any{
		(*AgentResponse_Authenticated_)(nil),
		(*AgentResponse_TrackData_)(nil),
		(*AgentResponse_TrackImage_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fishjam_agent_notifications_proto_rawDesc), len(file_fishjam_agent_notifications_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fishjam_agent_notifications_proto_goTypes,
		DependencyIndexes: file_fishjam_agent_notifications_proto_depIdxs,
		MessageInfos:      file_fishjam_agent_notifications_proto_msgTypes,
	}.Build()
	File_fishjam_agent_notifications_proto = out.File
	file_fishjam_agent_notifications_proto_goTypes = nil
	file_fishjam_agent_notifications_proto_depIdxs = nil
}
