// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: fishjam/peer_notifications.proto

package fishjam

import (
	peer "conference-to-stream/proto/fishjam/media_events/peer"
	server "conference-to-stream/proto/fishjam/media_events/server"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defines types of rooms peers may connect to
type PeerMessage_RoomType int32

const (
	PeerMessage_ROOM_TYPE_UNSPECIFIED PeerMessage_RoomType = 0
	PeerMessage_ROOM_TYPE_CONFERENCE  PeerMessage_RoomType = 1
	PeerMessage_ROOM_TYPE_AUDIO_ONLY  PeerMessage_RoomType = 2
	PeerMessage_ROOM_TYPE_LIVESTREAM  PeerMessage_RoomType = 3
)

// Enum value maps for PeerMessage_RoomType.
var (
	PeerMessage_RoomType_name = map[int32]string{
		0: "ROOM_TYPE_UNSPECIFIED",
		1: "ROOM_TYPE_CONFERENCE",
		2: "ROOM_TYPE_AUDIO_ONLY",
		3: "ROOM_TYPE_LIVESTREAM",
	}
	PeerMessage_RoomType_value = map[string]int32{
		"ROOM_TYPE_UNSPECIFIED": 0,
		"ROOM_TYPE_CONFERENCE":  1,
		"ROOM_TYPE_AUDIO_ONLY":  2,
		"ROOM_TYPE_LIVESTREAM":  3,
	}
)

func (x PeerMessage_RoomType) Enum() *PeerMessage_RoomType {
	p := new(PeerMessage_RoomType)
	*p = x
	return p
}

func (x PeerMessage_RoomType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerMessage_RoomType) Descriptor() protoreflect.EnumDescriptor {
	return file_fishjam_peer_notifications_proto_enumTypes[0].Descriptor()
}

func (PeerMessage_RoomType) Type() protoreflect.EnumType {
	return &file_fishjam_peer_notifications_proto_enumTypes[0]
}

func (x PeerMessage_RoomType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerMessage_RoomType.Descriptor instead.
func (PeerMessage_RoomType) EnumDescriptor() ([]byte, []int) {
	return file_fishjam_peer_notifications_proto_rawDescGZIP(), []int{0, 0}
}

type PeerMessage_SdkDeprecation_Status int32

const (
	PeerMessage_SdkDeprecation_STATUS_UNSPECIFIED PeerMessage_SdkDeprecation_Status = 0
	PeerMessage_SdkDeprecation_STATUS_UP_TO_DATE  PeerMessage_SdkDeprecation_Status = 1
	PeerMessage_SdkDeprecation_STATUS_DEPRECATED  PeerMessage_SdkDeprecation_Status = 2
	PeerMessage_SdkDeprecation_STATUS_UNSUPPORTED PeerMessage_SdkDeprecation_Status = 3
)

// Enum value maps for PeerMessage_SdkDeprecation_Status.
var (
	PeerMessage_SdkDeprecation_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_UP_TO_DATE",
		2: "STATUS_DEPRECATED",
		3: "STATUS_UNSUPPORTED",
	}
	PeerMessage_SdkDeprecation_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_UP_TO_DATE":  1,
		"STATUS_DEPRECATED":  2,
		"STATUS_UNSUPPORTED": 3,
	}
)

func (x PeerMessage_SdkDeprecation_Status) Enum() *PeerMessage_SdkDeprecation_Status {
	p := new(PeerMessage_SdkDeprecation_Status)
	*p = x
	return p
}

func (x PeerMessage_SdkDeprecation_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerMessage_SdkDeprecation_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_fishjam_peer_notifications_proto_enumTypes[1].Descriptor()
}

func (PeerMessage_SdkDeprecation_Status) Type() protoreflect.EnumType {
	return &file_fishjam_peer_notifications_proto_enumTypes[1]
}

func (x PeerMessage_SdkDeprecation_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerMessage_SdkDeprecation_Status.Descriptor instead.
func (PeerMessage_SdkDeprecation_Status) EnumDescriptor() ([]byte, []int) {
	return file_fishjam_peer_notifications_proto_rawDescGZIP(), []int{0, 0, 0}
}

// Defines any type of message sent between FJ and a peer
type PeerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*PeerMessage_Authenticated_
	//	*PeerMessage_AuthRequest_
	//	*PeerMessage_MediaEvent_
	//	*PeerMessage_RtcStatsReport
	//	*PeerMessage_PeerMediaEvent
	//	*PeerMessage_ServerMediaEvent
	Content       isPeerMessage_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerMessage) Reset() {
	*x = PeerMessage{}
	mi := &file_fishjam_peer_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerMessage) ProtoMessage() {}

func (x *PeerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_peer_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerMessage.ProtoReflect.Descriptor instead.
func (*PeerMessage) Descriptor() ([]byte, []int) {
	return file_fishjam_peer_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *PeerMessage) GetContent() isPeerMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *PeerMessage) GetAuthenticated() *PeerMessage_Authenticated {
	if x != nil {
		if x, ok := x.Content.(*PeerMessage_Authenticated_); ok {
			return x.Authenticated
		}
	}
	return nil
}

func (x *PeerMessage) GetAuthRequest() *PeerMessage_AuthRequest {
	if x != nil {
		if x, ok := x.Content.(*PeerMessage_AuthRequest_); ok {
			return x.AuthRequest
		}
	}
	return nil
}

func (x *PeerMessage) GetMediaEvent() *PeerMessage_MediaEvent {
	if x != nil {
		if x, ok := x.Content.(*PeerMessage_MediaEvent_); ok {
			return x.MediaEvent
		}
	}
	return nil
}

func (x *PeerMessage) GetRtcStatsReport() *PeerMessage_RTCStatsReport {
	if x != nil {
		if x, ok := x.Content.(*PeerMessage_RtcStatsReport); ok {
			return x.RtcStatsReport
		}
	}
	return nil
}

func (x *PeerMessage) GetPeerMediaEvent() *peer.MediaEvent {
	if x != nil {
		if x, ok := x.Content.(*PeerMessage_PeerMediaEvent); ok {
			return x.PeerMediaEvent
		}
	}
	return nil
}

func (x *PeerMessage) GetServerMediaEvent() *server.MediaEvent {
	if x != nil {
		if x, ok := x.Content.(*PeerMessage_ServerMediaEvent); ok {
			return x.ServerMediaEvent
		}
	}
	return nil
}

type isPeerMessage_Content interface {
	isPeerMessage_Content()
}

type PeerMessage_Authenticated_ struct {
	Authenticated *PeerMessage_Authenticated `protobuf:"bytes,1,opt,name=authenticated,proto3,oneof"`
}

type PeerMessage_AuthRequest_ struct {
	AuthRequest *PeerMessage_AuthRequest `protobuf:"bytes,2,opt,name=auth_request,json=authRequest,proto3,oneof"`
}

type PeerMessage_MediaEvent_ struct {
	MediaEvent *PeerMessage_MediaEvent `protobuf:"bytes,3,opt,name=media_event,json=mediaEvent,proto3,oneof"`
}

type PeerMessage_RtcStatsReport struct {
	RtcStatsReport *PeerMessage_RTCStatsReport `protobuf:"bytes,4,opt,name=rtc_stats_report,json=rtcStatsReport,proto3,oneof"`
}

type PeerMessage_PeerMediaEvent struct {
	PeerMediaEvent *peer.MediaEvent `protobuf:"bytes,5,opt,name=peer_media_event,json=peerMediaEvent,proto3,oneof"`
}

type PeerMessage_ServerMediaEvent struct {
	ServerMediaEvent *server.MediaEvent `protobuf:"bytes,6,opt,name=server_media_event,json=serverMediaEvent,proto3,oneof"`
}

func (*PeerMessage_Authenticated_) isPeerMessage_Content() {}

func (*PeerMessage_AuthRequest_) isPeerMessage_Content() {}

func (*PeerMessage_MediaEvent_) isPeerMessage_Content() {}

func (*PeerMessage_RtcStatsReport) isPeerMessage_Content() {}

func (*PeerMessage_PeerMediaEvent) isPeerMessage_Content() {}

func (*PeerMessage_ServerMediaEvent) isPeerMessage_Content() {}

// Deprecation status for SDK version
type PeerMessage_SdkDeprecation struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        PeerMessage_SdkDeprecation_Status `protobuf:"varint,1,opt,name=status,proto3,enum=fishjam.PeerMessage_SdkDeprecation_Status" json:"status,omitempty"`
	Message       string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerMessage_SdkDeprecation) Reset() {
	*x = PeerMessage_SdkDeprecation{}
	mi := &file_fishjam_peer_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerMessage_SdkDeprecation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerMessage_SdkDeprecation) ProtoMessage() {}

func (x *PeerMessage_SdkDeprecation) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_peer_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerMessage_SdkDeprecation.ProtoReflect.Descriptor instead.
func (*PeerMessage_SdkDeprecation) Descriptor() ([]byte, []int) {
	return file_fishjam_peer_notifications_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PeerMessage_SdkDeprecation) GetStatus() PeerMessage_SdkDeprecation_Status {
	if x != nil {
		return x.Status
	}
	return PeerMessage_SdkDeprecation_STATUS_UNSPECIFIED
}

func (x *PeerMessage_SdkDeprecation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Response sent by FJ, confirming successful authentication
type PeerMessage_Authenticated struct {
	state          protoimpl.MessageState      `protogen:"open.v1"`
	RoomType       PeerMessage_RoomType        `protobuf:"varint,1,opt,name=room_type,json=roomType,proto3,enum=fishjam.PeerMessage_RoomType" json:"room_type,omitempty"`
	SdkDeprecation *PeerMessage_SdkDeprecation `protobuf:"bytes,2,opt,name=sdk_deprecation,json=sdkDeprecation,proto3" json:"sdk_deprecation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PeerMessage_Authenticated) Reset() {
	*x = PeerMessage_Authenticated{}
	mi := &file_fishjam_peer_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerMessage_Authenticated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerMessage_Authenticated) ProtoMessage() {}

func (x *PeerMessage_Authenticated) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_peer_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerMessage_Authenticated.ProtoReflect.Descriptor instead.
func (*PeerMessage_Authenticated) Descriptor() ([]byte, []int) {
	return file_fishjam_peer_notifications_proto_rawDescGZIP(), []int{0, 1}
}

func (x *PeerMessage_Authenticated) GetRoomType() PeerMessage_RoomType {
	if x != nil {
		return x.RoomType
	}
	return PeerMessage_ROOM_TYPE_UNSPECIFIED
}

func (x *PeerMessage_Authenticated) GetSdkDeprecation() *PeerMessage_SdkDeprecation {
	if x != nil {
		return x.SdkDeprecation
	}
	return nil
}

// Request sent by peer, to authenticate to FJ server
type PeerMessage_AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	SdkVersion    string                 `protobuf:"bytes,2,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerMessage_AuthRequest) Reset() {
	*x = PeerMessage_AuthRequest{}
	mi := &file_fishjam_peer_notifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerMessage_AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerMessage_AuthRequest) ProtoMessage() {}

func (x *PeerMessage_AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_peer_notifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerMessage_AuthRequest.ProtoReflect.Descriptor instead.
func (*PeerMessage_AuthRequest) Descriptor() ([]byte, []int) {
	return file_fishjam_peer_notifications_proto_rawDescGZIP(), []int{0, 2}
}

func (x *PeerMessage_AuthRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PeerMessage_AuthRequest) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

// PeerConnection stats sent by peer
// https://developer.mozilla.org/en-US/docs/Web/API/RTCStatsReport#the_statistic_types
type PeerMessage_RTCStatsReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerMessage_RTCStatsReport) Reset() {
	*x = PeerMessage_RTCStatsReport{}
	mi := &file_fishjam_peer_notifications_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerMessage_RTCStatsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerMessage_RTCStatsReport) ProtoMessage() {}

func (x *PeerMessage_RTCStatsReport) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_peer_notifications_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerMessage_RTCStatsReport.ProtoReflect.Descriptor instead.
func (*PeerMessage_RTCStatsReport) Descriptor() ([]byte, []int) {
	return file_fishjam_peer_notifications_proto_rawDescGZIP(), []int{0, 3}
}

func (x *PeerMessage_RTCStatsReport) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// Any type of WebRTC messages passed between FJ and peer
type PeerMessage_MediaEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerMessage_MediaEvent) Reset() {
	*x = PeerMessage_MediaEvent{}
	mi := &file_fishjam_peer_notifications_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerMessage_MediaEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerMessage_MediaEvent) ProtoMessage() {}

func (x *PeerMessage_MediaEvent) ProtoReflect() protoreflect.Message {
	mi := &file_fishjam_peer_notifications_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerMessage_MediaEvent.ProtoReflect.Descriptor instead.
func (*PeerMessage_MediaEvent) Descriptor() ([]byte, []int) {
	return file_fishjam_peer_notifications_proto_rawDescGZIP(), []int{0, 4}
}

func (x *PeerMessage_MediaEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_fishjam_peer_notifications_proto protoreflect.FileDescriptor

const file_fishjam_peer_notifications_proto_rawDesc = "" +
	"\n" +
	" fishjam/peer_notifications.proto\x12\afishjam\x1a$fishjam/media_events/peer/peer.proto\x1a(fishjam/media_events/server/server.proto\"\xe4\b\n" +
	"\vPeerMessage\x12J\n" +
	"\rauthenticated\x18\x01 \x01(\v2\".fishjam.PeerMessage.AuthenticatedH\x00R\rauthenticated\x12E\n" +
	"\fauth_request\x18\x02 \x01(\v2 .fishjam.PeerMessage.AuthRequestH\x00R\vauthRequest\x12B\n" +
	"\vmedia_event\x18\x03 \x01(\v2\x1f.fishjam.PeerMessage.MediaEventH\x00R\n" +
	"mediaEvent\x12O\n" +
	"\x10rtc_stats_report\x18\x04 \x01(\v2#.fishjam.PeerMessage.RTCStatsReportH\x00R\x0ertcStatsReport\x12Q\n" +
	"\x10peer_media_event\x18\x05 \x01(\v2%.fishjam.media_events.peer.MediaEventH\x00R\x0epeerMediaEvent\x12W\n" +
	"\x12server_media_event\x18\x06 \x01(\v2'.fishjam.media_events.server.MediaEventH\x00R\x10serverMediaEvent\x1a\xd6\x01\n" +
	"\x0eSdkDeprecation\x12B\n" +
	"\x06status\x18\x01 \x01(\x0e2*.fishjam.PeerMessage.SdkDeprecation.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"f\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11STATUS_UP_TO_DATE\x10\x01\x12\x15\n" +
	"\x11STATUS_DEPRECATED\x10\x02\x12\x16\n" +
	"\x12STATUS_UNSUPPORTED\x10\x03\x1a\x99\x01\n" +
	"\rAuthenticated\x12:\n" +
	"\troom_type\x18\x01 \x01(\x0e2\x1d.fishjam.PeerMessage.RoomTypeR\broomType\x12L\n" +
	"\x0fsdk_deprecation\x18\x02 \x01(\v2#.fishjam.PeerMessage.SdkDeprecationR\x0esdkDeprecation\x1aD\n" +
	"\vAuthRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1f\n" +
	"\vsdk_version\x18\x02 \x01(\tR\n" +
	"sdkVersion\x1a$\n" +
	"\x0eRTCStatsReport\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x1a \n" +
	"\n" +
	"MediaEvent\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"s\n" +
	"\bRoomType\x12\x19\n" +
	"\x15ROOM_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ROOM_TYPE_CONFERENCE\x10\x01\x12\x18\n" +
	"\x14ROOM_TYPE_AUDIO_ONLY\x10\x02\x12\x18\n" +
	"\x14ROOM_TYPE_LIVESTREAM\x10\x03B\t\n" +
	"\acontentB$Z\"conference-to-stream/proto/fishjamb\x06proto3"

var (
	file_fishjam_peer_notifications_proto_rawDescOnce sync.Once
	file_fishjam_peer_notifications_proto_rawDescData []byte
)

func file_fishjam_peer_notifications_proto_rawDescGZIP() []byte {
	file_fishjam_peer_notifications_proto_rawDescOnce.Do(func() {
		file_fishjam_peer_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fishjam_peer_notifications_proto_rawDesc), len(file_fishjam_peer_notifications_proto_rawDesc)))
	})
	return file_fishjam_peer_notifications_proto_rawDescData
}

var file_fishjam_peer_notifications_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_fishjam_peer_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_fishjam_peer_notifications_proto_goTypes = []any{
	(PeerMessage_RoomType)(0),              // 0: fishjam.PeerMessage.RoomType
	(PeerMessage_SdkDeprecation_Status)(0), // 1: fishjam.PeerMessage.SdkDeprecation.Status
	(*PeerMessage)(nil),                    // 2: fishjam.PeerMessage
	(*PeerMessage_SdkDeprecation)(nil),     // 3: fishjam.PeerMessage.SdkDeprecation
	(*PeerMessage_Authenticated)(nil),      // 4: fishjam.PeerMessage.Authenticated
	(*PeerMessage_AuthRequest)(nil),        // 5: fishjam.PeerMessage.AuthRequest
	(*PeerMessage_RTCStatsReport)(nil),     // 6: fishjam.PeerMessage.RTCStatsReport
	(*PeerMessage_MediaEvent)(nil),         // 7: fishjam.PeerMessage.MediaEvent
	(*peer.MediaEvent)(nil),                // 8: fishjam.media_events.peer.MediaEvent
	(*server.MediaEvent)(nil),              // 9: fishjam.media_events.server.MediaEvent
}
var file_fishjam_peer_notifications_proto_depIdxs = []int32{
	4, // 0: fishjam.PeerMessage.authenticated:type_name -> fishjam.PeerMessage.Authenticated
	5, // 1: fishjam.PeerMessage.auth_request:type_name -> fishjam.PeerMessage.AuthRequest
	7, // 2: fishjam.PeerMessage.media_event:type_name -> fishjam.PeerMessage.MediaEvent
	6, // 3: fishjam.PeerMessage.rtc_stats_report:type_name -> fishjam.PeerMessage.RTCStatsReport
	8, // 4: fishjam.PeerMessage.peer_media_event:type_name -> fishjam.media_events.peer.MediaEvent
	9, // 5: fishjam.PeerMessage.server_media_event:type_name -> fishjam.media_events.server.MediaEvent
	1, // 6: fishjam.PeerMessage.SdkDeprecation.status:type_name -> fishjam.PeerMessage.SdkDeprecation.Status
	0, // 7: fishjam.PeerMessage.Authenticated.room_type:type_name -> fishjam.PeerMessage.RoomType
	3, // 8: fishjam.PeerMessage.Authenticated.sdk_deprecation:type_name -> fishjam.PeerMessage.SdkDeprecation
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_fishjam_peer_notifications_proto_init() }
func file_fishjam_peer_notifications_proto_init() {
	if File_fishjam_peer_notifications_proto != nil {
		return
	}
	file_fishjam_peer_notifications_proto_msgTypes[0].OneofWrappers = []any{
		(*PeerMessage_Authenticated_)(nil),
		(*PeerMessage_AuthRequest_)(nil),
		(*PeerMessage_MediaEvent_)(nil),
		(*PeerMessage_RtcStatsReport)(nil),
		(*PeerMessage_PeerMediaEvent)(nil),
		(*PeerMessage_ServerMediaEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fishjam_peer_notifications_proto_rawDesc), len(file_fishjam_peer_notifications_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fishjam_peer_notifications_proto_goTypes,
		DependencyIndexes: file_fishjam_peer_notifications_proto_depIdxs,
		EnumInfos:         file_fishjam_peer_notifications_proto_enumTypes,
		MessageInfos:      file_fishjam_peer_notifications_proto_msgTypes,
	}.Build()
	File_fishjam_peer_notifications_proto = out.File
	file_fishjam_peer_notifications_proto_goTypes = nil
	file_fishjam_peer_notifications_proto_depIdxs = nil
}
