name: Deploy Translation Demo as static page

on:
  push:
    branches: ["main"]
    paths:
      - "translation-demo/**"
      - ".github/workflows/translation-demo-deploy.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "translation-demo"
  cancel-in-progress: false

jobs:
  build-deploy:
    if: github.actor != 'dependabot[bot]'
    environment:
      name: translation-demo
      url: ${{ vars.TRANSLATION_DEMO_URL }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: translation-demo
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: "yarn"
          cache-dependency-path: ./translation-demo/yarn.lock

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build project
        run: yarn build

      - name: Copy files to deployment server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.TRANSLATION_DEMO_HOST }}
          username: ${{ secrets.TRANSLATION_DEMO_USERNAME }}
          key: ${{ secrets.TRANSLATION_DEMO_PRIVATE_KEY }}
          rm: true
          strip_components: 2
          source: translation-demo/dist/*
          target: ${{ secrets.TRANSLATION_DEMO_ROOT_DIR }}
